{"metadata":{"modules":[{"name":"Fusion"}],"roleHeading":"API Collection","title":"RawRepresentable Implementations","role":"collectionGroup"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/fusion\/asyncoperation\/state-swift.enum\/rawrepresentable-implementations"]}],"topicSections":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation\/State-swift.enum\/hashValue"],"generated":true,"title":"Instance Properties"},{"identifiers":["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation\/State-swift.enum\/hash(into:)"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation\/State-swift.enum"]]},"kind":"article","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation\/State-swift.enum\/RawRepresentable-Implementations"},"references":{"doc://org.cocoapods.Fusion/documentation/Fusion/AsyncOperation/State-swift.enum":{"navigatorTitle":[{"text":"State","kind":"identifier"}],"title":"AsyncOperation.State","type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"State","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/fusion\/asyncoperation\/state-swift.enum","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation\/State-swift.enum","abstract":[{"text":"An enumeration representing the state of an ","type":"text"},{"code":"AsyncOperation","type":"codeVoice"},{"text":".","type":"text"}]},"doc://org.cocoapods.Fusion/documentation/Fusion/AsyncOperation/State-swift.enum/hashValue":{"conformance":{"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"RawValue"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":".","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}]},"title":"hashValue","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"kind":"symbol","url":"\/documentation\/fusion\/asyncoperation\/state-swift.enum\/hashvalue","abstract":[],"identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation\/State-swift.enum\/hashValue"},"doc://org.cocoapods.Fusion/documentation/Fusion/AsyncOperation":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation","title":"AsyncOperation","abstract":[{"text":"A subclass of ","type":"text"},{"type":"codeVoice","code":"Operation"},{"text":" that represents an asynchronous operation.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"AsyncOperation","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AsyncOperation","kind":"identifier"}],"url":"\/documentation\/fusion\/asyncoperation","type":"topic"},"doc://org.cocoapods.Fusion/documentation/Fusion":{"url":"\/documentation\/fusion","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion","type":"topic","title":"Fusion","abstract":[],"role":"collection"},"doc://org.cocoapods.Fusion/documentation/Fusion/AsyncOperation/State-swift.enum/hash(into:)":{"url":"\/documentation\/fusion\/asyncoperation\/state-swift.enum\/hash(into:)","role":"symbol","conformance":{"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}]},"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"Hasher","preciseIdentifier":"s:s6HasherV"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation\/State-swift.enum\/hash(into:)","type":"topic","title":"hash(into:)","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1AsyncOperation\/title","op":"replace","value":"AsyncOperation"},{"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1AsyncOperation\/fragments","op":"replace","value":[{"kind":"identifier","text":"AsyncOperation"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1AsyncOperation\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AsyncOperation"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}