disabled_rules:
  - colon
  - type_name
  - trailing_whitespace
  - function_body_length
  - type_body_length
  - vertical_parameter_alignment
  - identifier_name
  
line_length:
  - 150

file_length:
  - 500

included:
  - Account
