{"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperationQueue","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/GradientView","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/Keychain","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/RESTAuthenticator","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/ThreadSafe","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/TimerControl","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/Tween","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/UIHorizontalPanGestureRecognizer"],"title":"Classes","generated":true,"anchor":"Classes"},{"identifiers":["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/DataBindable","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/DataManageable","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/DataStorageable","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/ImageConvertible","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/Searcheable","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/TextConvertible","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/TweenDelegate"],"title":"Protocols","generated":true,"anchor":"Protocols"},{"identifiers":["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AnyCodable","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncImageCached","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/Constant","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/ControlAction","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/CountryInfo","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/FontLoader","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/HapticControl","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/InMemoryCache","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/KeyPathName","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/Line","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/LogEntry","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PressEffect","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/RESTBuilder","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/RGB","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/RectCorners","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/RectEdges","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/RoundedCorner","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/StateStorage","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/Stored","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/StoredReadOnly","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/SwipeToDismiss","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/TextUpdateModifier","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/UIKitView","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/UIKitViewController","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/UserFlow","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/UserFlowHook","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/UserFlowUniversalLink"],"title":"Structures","generated":true,"anchor":"Structures"},{"identifiers":["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/kFusionCoreName","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/kFusionCoreVersion","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/kFusionUIName","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/kFusionUIVersion"],"title":"Variables","generated":true,"anchor":"Variables"},{"identifiers":["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/asyncGlobal(qos:callback:)","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/asyncMain(_:)","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/asyncMain(after:_:)","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/asyncResponse(_:)","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/syncMain(_:)"],"title":"Functions","generated":true,"anchor":"Functions"},{"identifiers":["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/!=(_:_:)","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/==(_:_:)"],"title":"Operators","generated":true,"anchor":"Operators"},{"identifiers":["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncTask","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/Callback","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/ConfirmationCallback","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/ControlHandler","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/Easing","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/FPoint","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/HTTPCookieInfo","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/Headers","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/ImageDownloadCallback","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/ImageLoadOrDownloadCallback","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/Input","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/LogString","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/Response","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/TextAttributes","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/TimerCallback","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/TweenCallback","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/UserFlowMapping"],"title":"Type Aliases","generated":true,"anchor":"Type-Aliases"},{"identifiers":["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/Ease","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/HTTPMethod","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/Logger","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationStyle","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/RESTError"],"title":"Enumerations","generated":true,"anchor":"Enumerations"},{"identifiers":["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/CoreFoundation","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/CoreGraphics","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/Dispatch","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/Foundation","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/ObjectiveC","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/QuartzCore","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/Swift","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/SwiftUICore","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/UIKit","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/UIUtilities","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/UserNotifications"],"title":"Extended Modules","generated":true,"anchor":"Extended-Modules"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/fusion"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/fusion"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"metadata":{"role":"collection","title":"Fusion","roleHeading":"Framework","modules":[{"name":"Fusion"}],"externalID":"Fusion","symbolKind":"module"},"hierarchy":{"paths":[[]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion"},"kind":"symbol","references":{"doc://org.cocoapods.Fusion/documentation/Fusion/FusionVersionString":{"abstract":[],"kind":"symbol","role":"symbol","type":"topic","title":"FusionVersionString","fragments":[{"kind":"identifier","text":"FusionVersionString"}],"url":"\/documentation\/fusion\/fusionversionstring","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/FusionVersionString"},"doc://org.cocoapods.Fusion/documentation/Fusion/CoreGraphics":{"kind":"symbol","role":"collection","type":"topic","title":"CoreGraphics","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/CoreGraphics","url":"\/documentation\/fusion\/coregraphics","abstract":[]},"doc://org.cocoapods.Fusion/documentation/Fusion/ControlAction":{"role":"symbol","url":"\/documentation\/fusion\/controlaction","navigatorTitle":[{"kind":"identifier","text":"ControlAction"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ControlAction"}],"type":"topic","title":"ControlAction","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/ControlAction"},"doc://org.cocoapods.Fusion/documentation/Fusion/RESTBuilder":{"url":"\/documentation\/fusion\/restbuilder","title":"RESTBuilder","kind":"symbol","navigatorTitle":[{"text":"RESTBuilder","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RESTBuilder","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/RESTBuilder","abstract":[],"role":"symbol","type":"topic"},"doc://org.cocoapods.Fusion/documentation/Fusion/Dispatch":{"title":"Dispatch","url":"\/documentation\/fusion\/dispatch","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/Dispatch","type":"topic","role":"collection"},"doc://org.cocoapods.Fusion/documentation/Fusion/GradientView":{"title":"GradientView","url":"\/documentation\/fusion\/gradientview","abstract":[{"text":"Convenience view that encpsulates the ","type":"text"},{"code":"UIView.make(gradient:start:end:type:)","type":"codeVoice"},{"text":" and makes it automatically redrawable and adaptable.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/GradientView","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GradientView"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GradientView"}]},"doc://org.cocoapods.Fusion/documentation/Fusion/kFusionCoreVersion":{"navigatorTitle":[{"text":"kFusionCoreVersion","kind":"identifier"}],"title":"kFusionCoreVersion","type":"topic","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kFusionCoreVersion","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"kind":"symbol","url":"\/documentation\/fusion\/kfusioncoreversion","abstract":[],"identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/kFusionCoreVersion"},"doc://org.cocoapods.Fusion/documentation/Fusion/FPoint":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/FPoint","navigatorTitle":[{"text":"FPoint","kind":"identifier"}],"title":"FPoint","abstract":[{"text":"Basic floating point data type.","type":"text"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"FPoint"}],"url":"\/documentation\/fusion\/fpoint"},"doc://org.cocoapods.Fusion/documentation/Fusion/UIHorizontalPanGestureRecognizer":{"url":"\/documentation\/fusion\/uihorizontalpangesturerecognizer","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/UIHorizontalPanGestureRecognizer","navigatorTitle":[{"kind":"identifier","text":"UIHorizontalPanGestureRecognizer"}],"type":"topic","title":"UIHorizontalPanGestureRecognizer","abstract":[{"text":"Same as Pan Gesture but stricly horizontal, ideal for swipe cell\/object actions.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIHorizontalPanGestureRecognizer"}],"role":"symbol"},"doc://org.cocoapods.Fusion/documentation/Fusion/UIKitViewController":{"title":"UIKitViewController","url":"\/documentation\/fusion\/uikitviewcontroller","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/UIKitViewController","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIKitViewController","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"UIKitViewController","kind":"identifier"}]},"doc://org.cocoapods.Fusion/documentation/Fusion":{"url":"\/documentation\/fusion","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion","type":"topic","title":"Fusion","abstract":[],"role":"collection"},"doc://org.cocoapods.Fusion/documentation/Fusion/Response":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Response"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/Response","url":"\/documentation\/fusion\/response","abstract":[],"title":"Response","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"Response"}]},"doc://org.cocoapods.Fusion/documentation/Fusion/SwiftUICore":{"role":"collection","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/SwiftUICore","title":"SwiftUICore","abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/fusion\/swiftuicore"},"doc://org.cocoapods.Fusion/documentation/Fusion/SwipeToDismiss":{"navigatorTitle":[{"text":"SwipeToDismiss","kind":"identifier"}],"type":"topic","title":"SwipeToDismiss","role":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/SwipeToDismiss","url":"\/documentation\/fusion\/swipetodismiss","abstract":[{"text":"A view modifier that enables swipe-to-dismiss functionality for views.","type":"text"},{"text":" ","type":"text"},{"text":"Users can swipe in the specified direction to trigger a dismiss action.","type":"text"},{"text":" ","type":"text"},{"text":"The view will follow the drag gesture and dismiss when swiped beyond a threshold.","type":"text"}],"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SwipeToDismiss","kind":"identifier"}]},"doc://org.cocoapods.Fusion/documentation/Fusion/==(_:_:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/==(_:_:)","kind":"symbol","abstract":[],"url":"\/documentation\/fusion\/==(_:_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"=="},{"kind":"text","text":" "},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"T"},{"text":", ","kind":"text"},{"text":"V","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"KeyPath","kind":"typeIdentifier","preciseIdentifier":"s:s7KeyPathC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:6Fusion2eeoiySbxcs7KeyPathCyxq_G_q_tSQR_r0_lF1TL_xmfp","text":"T"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:6Fusion2eeoiySbxcs7KeyPathCyxq_G_q_tSQR_r0_lF1VL_q_mfp","text":"V"},{"text":">, ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:6Fusion2eeoiySbxcs7KeyPathCyxq_G_q_tSQR_r0_lF1VL_q_mfp","text":"V"},{"kind":"text","text":") -> ("},{"kind":"typeIdentifier","preciseIdentifier":"s:6Fusion2eeoiySbxcs7KeyPathCyxq_G_q_tSQR_r0_lF1TL_xmfp","text":"T"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"==(_:_:)"},"doc://org.cocoapods.Fusion/documentation/Fusion/AnyCodable":{"url":"\/documentation\/fusion\/anycodable","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AnyCodable","navigatorTitle":[{"kind":"identifier","text":"AnyCodable"}],"type":"topic","title":"AnyCodable","abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnyCodable"}],"role":"symbol"},"doc://org.cocoapods.Fusion/documentation/Fusion/AsyncOperationQueue":{"navigatorTitle":[{"kind":"identifier","text":"AsyncOperationQueue"}],"title":"AsyncOperationQueue","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AsyncOperationQueue"}],"kind":"symbol","url":"\/documentation\/fusion\/asyncoperationqueue","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperationQueue","abstract":[{"type":"text","text":"A class that manages a queue of "},{"code":"AsyncOperation","type":"codeVoice"},{"type":"text","text":" tasks, allowing control over the maximum number of concurrent tasks."}]},"doc://org.cocoapods.Fusion/documentation/Fusion/HapticControl":{"url":"\/documentation\/fusion\/hapticcontrol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HapticControl"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"HapticControl"}],"identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/HapticControl","type":"topic","title":"HapticControl","abstract":[{"type":"text","text":"Global Haptic control for various types of different vibrations."}]},"doc://org.cocoapods.Fusion/documentation/Fusion/PresentationController":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController","navigatorTitle":[{"kind":"identifier","text":"PresentationController"}],"title":"PresentationController","abstract":[{"type":"text","text":"A presentation controller that has a dimming view and presents from the bottom, as a drawer behavior."}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PresentationController"}],"url":"\/documentation\/fusion\/presentationcontroller"},"doc://org.cocoapods.Fusion/documentation/Fusion/ImageDownloadCallback":{"kind":"symbol","navigatorTitle":[{"text":"ImageDownloadCallback","kind":"identifier"}],"role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageDownloadCallback","kind":"identifier"}],"type":"topic","title":"ImageDownloadCallback","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/ImageDownloadCallback","url":"\/documentation\/fusion\/imagedownloadcallback","abstract":[]},"doc://org.cocoapods.Fusion/documentation/Fusion/LogString":{"type":"topic","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/LogString","kind":"symbol","abstract":[],"url":"\/documentation\/fusion\/logstring","role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"LogString"}],"navigatorTitle":[{"kind":"identifier","text":"LogString"}],"title":"LogString"},"doc://org.cocoapods.Fusion/documentation/Fusion/RectEdges":{"title":"RectEdges","url":"\/documentation\/fusion\/rectedges","abstract":[{"type":"text","text":"Represents the edges of a rectangle with individual values for each side."}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/RectEdges","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"RectEdges"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"RectEdges"}]},"doc://org.cocoapods.Fusion/documentation/Fusion/FontLoader":{"navigatorTitle":[{"kind":"identifier","text":"FontLoader"}],"type":"topic","title":"FontLoader","role":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/FontLoader","url":"\/documentation\/fusion\/fontloader","abstract":[{"type":"text","text":"Loads the font inside the compiled collection of bundles."}],"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FontLoader"}]},"doc://org.cocoapods.Fusion/documentation/Fusion/asyncMain(after:_:)":{"title":"asyncMain(after:_:)","url":"\/documentation\/fusion\/asyncmain(after:_:)","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/asyncMain(after:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"asyncMain"},{"kind":"text","text":"("},{"kind":"externalParam","text":"after"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":", () -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"type":"topic","role":"symbol"},"doc://org.cocoapods.Fusion/documentation/Fusion/ImageConvertible":{"navigatorTitle":[{"text":"ImageConvertible","kind":"identifier"}],"title":"ImageConvertible","type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageConvertible","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/fusion\/imageconvertible","abstract":[],"identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/ImageConvertible"},"doc://org.cocoapods.Fusion/documentation/Fusion/PresentationStyle":{"url":"\/documentation\/fusion\/presentationstyle","title":"PresentationStyle","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PresentationStyle"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PresentationStyle"}],"identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationStyle","abstract":[],"role":"symbol","type":"topic"},"doc://org.cocoapods.Fusion/documentation/Fusion/Swift":{"kind":"symbol","role":"collection","type":"topic","title":"Swift","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/Swift","url":"\/documentation\/fusion\/swift","abstract":[]},"doc://org.cocoapods.Fusion/documentation/Fusion/Ease":{"abstract":[],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Ease"}],"url":"\/documentation\/fusion\/ease","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/Ease","title":"Ease","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Ease"}]},"doc://org.cocoapods.Fusion/documentation/Fusion/HTTPMethod":{"url":"\/documentation\/fusion\/httpmethod","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HTTPMethod"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HTTPMethod"}],"identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/HTTPMethod","type":"topic","abstract":[],"title":"HTTPMethod"},"doc://org.cocoapods.Fusion/documentation/Fusion/TweenDelegate":{"type":"topic","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/TweenDelegate","kind":"symbol","abstract":[],"url":"\/documentation\/fusion\/tweendelegate","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TweenDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"TweenDelegate"}],"title":"TweenDelegate"},"doc://org.cocoapods.Fusion/documentation/Fusion/CountryInfo":{"navigatorTitle":[{"text":"CountryInfo","kind":"identifier"}],"type":"topic","title":"CountryInfo","role":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/CountryInfo","url":"\/documentation\/fusion\/countryinfo","abstract":[{"type":"text","text":"A structure that provides comprehensive information about a country."}],"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"CountryInfo","kind":"identifier"}]},"doc://org.cocoapods.Fusion/documentation/Fusion/LogEntry":{"type":"topic","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/LogEntry","kind":"symbol","abstract":[{"type":"text","text":"A structure that represents a log entry with a "},{"code":"basic","type":"codeVoice"},{"type":"text","text":" and "},{"code":"full","type":"codeVoice"},{"type":"text","text":" log message."}],"url":"\/documentation\/fusion\/logentry","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LogEntry"}],"navigatorTitle":[{"kind":"identifier","text":"LogEntry"}],"title":"LogEntry"},"doc://org.cocoapods.Fusion/documentation/Fusion/UserFlowUniversalLink":{"kind":"symbol","navigatorTitle":[{"text":"UserFlowUniversalLink","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserFlowUniversalLink"}],"type":"topic","title":"UserFlowUniversalLink","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/UserFlowUniversalLink","url":"\/documentation\/fusion\/userflowuniversallink","abstract":[]},"doc://org.cocoapods.Fusion/documentation/Fusion/Input":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/Input","navigatorTitle":[{"kind":"identifier","text":"Input"}],"title":"Input","abstract":[],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"Input"}],"url":"\/documentation\/fusion\/input"},"doc://org.cocoapods.Fusion/documentation/Fusion/RGB":{"url":"\/documentation\/fusion\/rgb","title":"RGB","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"RGB"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"RGB"}],"identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/RGB","abstract":[],"role":"symbol","type":"topic"},"doc://org.cocoapods.Fusion/documentation/Fusion/AsyncTask":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncTask","title":"AsyncTask","abstract":[{"text":"A type alias for an asynchronous task that takes an ","type":"text"},{"code":"AsyncOperation","type":"codeVoice"},{"text":" instance and returns ","type":"text"},{"code":"Void","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"AsyncTask","kind":"identifier"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AsyncTask","kind":"identifier"}],"url":"\/documentation\/fusion\/asynctask","type":"topic"},"doc://org.cocoapods.Fusion/documentation/Fusion/TimerControl":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TimerControl"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/TimerControl","url":"\/documentation\/fusion\/timercontrol","title":"TimerControl","abstract":[{"type":"text","text":"This class creates a single unique loop running with the interval defined by the constant "},{"identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/Constant\/maxFps","type":"reference","isActive":true},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TimerControl"}]},"doc://org.cocoapods.Fusion/documentation/Fusion/RESTAuthenticator":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"RESTAuthenticator","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/RESTAuthenticator","url":"\/documentation\/fusion\/restauthenticator","title":"RESTAuthenticator","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RESTAuthenticator","kind":"identifier"}]},"doc://org.cocoapods.Fusion/documentation/Fusion/InMemoryCache":{"url":"\/documentation\/fusion\/inmemorycache","title":"InMemoryCache","kind":"symbol","navigatorTitle":[{"text":"InMemoryCache","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InMemoryCache","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/InMemoryCache","abstract":[{"text":"In memory key\/value cache that works as a lightening cache layer 2 over any other storage.","type":"text"},{"text":" ","type":"text"},{"text":"It allows the value to be read from the cache or if not found allows the caller to set it.","type":"text"}],"role":"symbol","type":"topic"},"doc://org.cocoapods.Fusion/documentation/Fusion/ThreadSafe":{"url":"\/documentation\/fusion\/threadsafe","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ThreadSafe"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ThreadSafe"}],"identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/ThreadSafe","type":"topic","title":"ThreadSafe","abstract":[]},"doc://org.cocoapods.Fusion/documentation/Fusion/Stored":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"Stored"}],"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Stored"}],"type":"topic","title":"Stored","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/Stored","url":"\/documentation\/fusion\/stored","kind":"symbol"},"doc://org.cocoapods.Fusion/documentation/Fusion/Constant":{"url":"\/documentation\/fusion\/constant","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Constant"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Constant"}],"identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/Constant","type":"topic","title":"Constant","abstract":[]},"doc://org.cocoapods.Fusion/documentation/Fusion/kFusionUIVersion":{"kind":"symbol","navigatorTitle":[{"text":"kFusionUIVersion","kind":"identifier"}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kFusionUIVersion","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"type":"topic","title":"kFusionUIVersion","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/kFusionUIVersion","url":"\/documentation\/fusion\/kfusionuiversion","abstract":[]},"doc://org.cocoapods.Fusion/documentation/Fusion/Callback":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/Callback","navigatorTitle":[{"kind":"identifier","text":"Callback"}],"title":"Callback","abstract":[],"kind":"symbol","type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Callback","kind":"identifier"}],"url":"\/documentation\/fusion\/callback"},"doc://org.cocoapods.Fusion/documentation/Fusion/AsyncImageCached":{"navigatorTitle":[{"kind":"identifier","text":"AsyncImageCached"}],"title":"AsyncImageCached","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AsyncImageCached"}],"kind":"symbol","url":"\/documentation\/fusion\/asyncimagecached","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncImageCached","abstract":[]},"doc://org.cocoapods.Fusion/documentation/Fusion/ObjectiveC":{"type":"topic","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/ObjectiveC","kind":"symbol","abstract":[],"url":"\/documentation\/fusion\/objectivec","role":"collection","title":"ObjectiveC"},"doc://org.cocoapods.Fusion/documentation/Fusion/RoundedCorner":{"url":"\/documentation\/fusion\/roundedcorner","title":"RoundedCorner","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"RoundedCorner"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"RoundedCorner"}],"identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/RoundedCorner","abstract":[{"text":"A shape that applies rounded corners to specific corners of a rectangle.","type":"text"},{"text":" ","type":"text"},{"text":"This shape allows you to round only selected corners rather than all corners uniformly,","type":"text"},{"text":" ","type":"text"},{"text":"providing more flexible corner radius customization for views.","type":"text"}],"role":"symbol","type":"topic"},"doc://org.cocoapods.Fusion/documentation/Fusion/asyncResponse(_:)":{"role":"symbol","url":"\/documentation\/fusion\/asyncresponse(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"asyncResponse","kind":"identifier"},{"text":"<","kind":"text"},{"text":"T","kind":"genericParameter"},{"text":">(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:6Fusion8Responsea","text":"Response"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:6Fusion13asyncResponseyys6ResultOyxs5Error_pG_So13NSURLResponseCSgtcyAF_AItcSglF1TL_xmfp","text":"T"},{"text":">?) -> ","kind":"text"},{"preciseIdentifier":"s:6Fusion8Responsea","text":"Response","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:6Fusion13asyncResponseyys6ResultOyxs5Error_pG_So13NSURLResponseCSgtcyAF_AItcSglF1TL_xmfp","text":"T","kind":"typeIdentifier"},{"text":">","kind":"text"}],"type":"topic","title":"asyncResponse(_:)","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/asyncResponse(_:)"},"doc://org.cocoapods.Fusion/documentation/Fusion/StateStorage":{"navigatorTitle":[{"kind":"identifier","text":"StateStorage"}],"title":"StateStorage","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"StateStorage"}],"kind":"symbol","url":"\/documentation\/fusion\/statestorage","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/StateStorage","abstract":[{"text":"Key-Value temporary in memory storage (RAM). ","type":"text"},{"code":"Codable","type":"codeVoice"},{"text":" Objects can be added and removed from this shared","type":"text"},{"text":" ","type":"text"},{"text":"storage.","type":"text"}]},"doc://org.cocoapods.Fusion/documentation/Fusion/StoredReadOnly":{"abstract":[],"navigatorTitle":[{"text":"StoredReadOnly","kind":"identifier"}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StoredReadOnly","kind":"identifier"}],"type":"topic","title":"StoredReadOnly","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/StoredReadOnly","url":"\/documentation\/fusion\/storedreadonly","kind":"symbol"},"doc://org.cocoapods.Fusion/documentation/Fusion/Line":{"kind":"symbol","title":"Line","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/Line","abstract":[{"type":"text","text":"Represents a line segment with a start and an end point."}],"role":"symbol","navigatorTitle":[{"text":"Line","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Line","kind":"identifier"}],"url":"\/documentation\/fusion\/line","type":"topic"},"doc://org.cocoapods.Fusion/documentation/Fusion/UserFlowHook":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/UserFlowHook","title":"UserFlowHook","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UserFlowHook"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserFlowHook"}],"url":"\/documentation\/fusion\/userflowhook","type":"topic"},"doc://org.cocoapods.Fusion/documentation/Fusion/QuartzCore":{"url":"\/documentation\/fusion\/quartzcore","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/QuartzCore","type":"topic","title":"QuartzCore","abstract":[],"role":"collection"},"doc://org.cocoapods.Fusion/documentation/Fusion/Constant/maxFps":{"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/Constant\/maxFps","url":"\/documentation\/fusion\/constant\/maxfps","title":"maxFps","abstract":[],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxFps"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:6Fusion6FPointa","text":"FPoint"}]},"doc://org.cocoapods.Fusion/documentation/Fusion/Tween":{"url":"\/documentation\/fusion\/tween","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/Tween","navigatorTitle":[{"text":"Tween","kind":"identifier"}],"type":"topic","title":"Tween","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Tween"}],"role":"symbol"},"doc://org.cocoapods.Fusion/documentation/Fusion/TimerCallback":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TimerCallback"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/TimerCallback","url":"\/documentation\/fusion\/timercallback","title":"TimerCallback","abstract":[],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TimerCallback"}]},"doc://org.cocoapods.Fusion/documentation/Fusion/TweenCallback":{"abstract":[],"kind":"symbol","role":"symbol","type":"topic","title":"TweenCallback","navigatorTitle":[{"kind":"identifier","text":"TweenCallback"}],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"TweenCallback"}],"url":"\/documentation\/fusion\/tweencallback","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/TweenCallback"},"doc://org.cocoapods.Fusion/documentation/Fusion/!=(_:_:)":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"T"},{"kind":"text","text":", "},{"kind":"genericParameter","text":"V"},{"kind":"text","text":">("},{"kind":"typeIdentifier","preciseIdentifier":"s:s7KeyPathC","text":"KeyPath"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:6Fusion2neoiySbxcs7KeyPathCyxq_G_q_tSQR_r0_lF1TL_xmfp","text":"T"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:6Fusion2neoiySbxcs7KeyPathCyxq_G_q_tSQR_r0_lF1VL_q_mfp","text":"V"},{"kind":"text","text":">, "},{"kind":"typeIdentifier","preciseIdentifier":"s:6Fusion2neoiySbxcs7KeyPathCyxq_G_q_tSQR_r0_lF1VL_q_mfp","text":"V"},{"kind":"text","text":") -> ("},{"kind":"typeIdentifier","preciseIdentifier":"s:6Fusion2neoiySbxcs7KeyPathCyxq_G_q_tSQR_r0_lF1TL_xmfp","text":"T"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic","title":"!=(_:_:)","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/!=(_:_:)","url":"\/documentation\/fusion\/!=(_:_:)","abstract":[]},"doc://org.cocoapods.Fusion/documentation/Fusion/UserFlow":{"url":"\/documentation\/fusion\/userflow","role":"symbol","navigatorTitle":[{"text":"UserFlow","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UserFlow","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/UserFlow","type":"topic","abstract":[],"title":"UserFlow"},"doc://org.cocoapods.Fusion/documentation/Fusion/RectCorners":{"type":"topic","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/RectCorners","kind":"symbol","abstract":[{"text":"Represents the corner radii of a rectangle with individual values for each corner.","type":"text"}],"url":"\/documentation\/fusion\/rectcorners","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"RectCorners"}],"navigatorTitle":[{"kind":"identifier","text":"RectCorners"}],"title":"RectCorners"},"doc://org.cocoapods.Fusion/documentation/Fusion/UserFlowMapping":{"navigatorTitle":[{"text":"UserFlowMapping","kind":"identifier"}],"title":"UserFlowMapping","type":"topic","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UserFlowMapping","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/fusion\/userflowmapping","abstract":[],"identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/UserFlowMapping"},"doc://org.cocoapods.Fusion/documentation/Fusion/ControlHandler":{"title":"ControlHandler","url":"\/documentation\/fusion\/controlhandler","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/ControlHandler","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ControlHandler","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"ControlHandler","kind":"identifier"}]},"doc://org.cocoapods.Fusion/documentation/Fusion/CoreFoundation":{"title":"CoreFoundation","type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/fusion\/corefoundation","abstract":[],"identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/CoreFoundation"},"doc://org.cocoapods.Fusion/documentation/Fusion/kFusionUIName":{"title":"kFusionUIName","url":"\/documentation\/fusion\/kfusionuiname","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/kFusionUIName","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"kFusionUIName"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"kFusionUIName","kind":"identifier"}]},"doc://org.cocoapods.Fusion/documentation/Fusion/Headers":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/Headers","title":"Headers","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Headers"}],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"Headers"}],"url":"\/documentation\/fusion\/headers","type":"topic"},"doc://org.cocoapods.Fusion/documentation/Fusion/ImageLoadOrDownloadCallback":{"navigatorTitle":[{"text":"ImageLoadOrDownloadCallback","kind":"identifier"}],"title":"ImageLoadOrDownloadCallback","type":"topic","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageLoadOrDownloadCallback","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/fusion\/imageloadordownloadcallback","abstract":[],"identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/ImageLoadOrDownloadCallback"},"doc://org.cocoapods.Fusion/documentation/Fusion/Foundation":{"title":"Foundation","type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/fusion\/foundation","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/Foundation","abstract":[]},"doc://org.cocoapods.Fusion/documentation/Fusion/PressEffect":{"kind":"symbol","navigatorTitle":[{"text":"PressEffect","kind":"identifier"}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PressEffect","kind":"identifier"}],"type":"topic","title":"PressEffect","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PressEffect","url":"\/documentation\/fusion\/presseffect","abstract":[{"type":"text","text":"A view modifier that provides visual feedback when the user presses on a view."},{"text":" ","type":"text"},{"type":"text","text":"This modifier applies scale and opacity changes to simulate a press effect,"},{"type":"text","text":" "},{"type":"text","text":"commonly used for buttons and interactive elements."}]},"doc://org.cocoapods.Fusion/documentation/Fusion/HTTPCookieInfo":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/HTTPCookieInfo","navigatorTitle":[{"text":"HTTPCookieInfo","kind":"identifier"}],"title":"HTTPCookieInfo","abstract":[],"kind":"symbol","type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HTTPCookieInfo","kind":"identifier"}],"url":"\/documentation\/fusion\/httpcookieinfo"},"doc://org.cocoapods.Fusion/documentation/Fusion/AsyncOperation":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation","title":"AsyncOperation","abstract":[{"text":"A subclass of ","type":"text"},{"type":"codeVoice","code":"Operation"},{"text":" that represents an asynchronous operation.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"AsyncOperation","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AsyncOperation","kind":"identifier"}],"url":"\/documentation\/fusion\/asyncoperation","type":"topic"},"doc://org.cocoapods.Fusion/documentation/Fusion/Searcheable":{"navigatorTitle":[{"text":"Searcheable","kind":"identifier"}],"title":"Searcheable","type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Searcheable","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/fusion\/searcheable","abstract":[],"identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/Searcheable"},"doc://org.cocoapods.Fusion/documentation/Fusion/DataManageable":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/DataManageable","navigatorTitle":[{"kind":"identifier","text":"DataManageable"}],"title":"DataManageable","abstract":[{"type":"text","text":"A protocol that provides comprehensive data management capabilities with optimized caching and optional throttled persistence."}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DataManageable"}],"url":"\/documentation\/fusion\/datamanageable"},"doc://org.cocoapods.Fusion/documentation/Fusion/asyncMain(_:)":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"asyncMain"},{"kind":"text","text":"(() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"type":"topic","title":"asyncMain(_:)","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/asyncMain(_:)","url":"\/documentation\/fusion\/asyncmain(_:)","abstract":[]},"doc://org.cocoapods.Fusion/documentation/Fusion/UIKitView":{"abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIKitView"}],"url":"\/documentation\/fusion\/uikitview","kind":"symbol","role":"symbol","type":"topic","title":"UIKitView","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/UIKitView","navigatorTitle":[{"kind":"identifier","text":"UIKitView"}]},"doc://org.cocoapods.Fusion/documentation/Fusion/UIUtilities":{"role":"collection","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/UIUtilities","title":"UIUtilities","abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/fusion\/uiutilities"},"doc://org.cocoapods.Fusion/documentation/Fusion/UserNotifications":{"type":"topic","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/UserNotifications","kind":"symbol","abstract":[],"url":"\/documentation\/fusion\/usernotifications","role":"collection","title":"UserNotifications"},"doc://org.cocoapods.Fusion/documentation/Fusion/DataStorageable":{"url":"\/documentation\/fusion\/datastorageable","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/DataStorageable","navigatorTitle":[{"text":"DataStorageable","kind":"identifier"}],"type":"topic","title":"DataStorageable","abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DataStorageable","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.Fusion/documentation/Fusion/TextAttributes":{"navigatorTitle":[{"text":"TextAttributes","kind":"identifier"}],"type":"topic","title":"TextAttributes","role":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/TextAttributes","url":"\/documentation\/fusion\/textattributes","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"TextAttributes"}]},"doc://org.cocoapods.Fusion/documentation/Fusion/kFusionCoreName":{"role":"symbol","url":"\/documentation\/fusion\/kfusioncorename","navigatorTitle":[{"kind":"identifier","text":"kFusionCoreName"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"kFusionCoreName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"type":"topic","title":"kFusionCoreName","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/kFusionCoreName"},"doc://org.cocoapods.Fusion/documentation/Fusion/asyncGlobal(qos:callback:)":{"title":"asyncGlobal(qos:callback:)","url":"\/documentation\/fusion\/asyncglobal(qos:callback:)","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/asyncGlobal(qos:callback:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"asyncGlobal"},{"kind":"text","text":"("},{"kind":"externalParam","text":"qos"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:8Dispatch0A3QoSV","text":"DispatchQoS"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:8Dispatch0A3QoSV0B6SClassO","text":"QoSClass"},{"kind":"text","text":", "},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": () -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"type":"topic","role":"symbol"},"doc://org.cocoapods.Fusion/documentation/Fusion/TextConvertible":{"abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TextConvertible","kind":"identifier"}],"url":"\/documentation\/fusion\/textconvertible","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/TextConvertible","title":"TextConvertible","type":"topic","navigatorTitle":[{"text":"TextConvertible","kind":"identifier"}]},"doc://org.cocoapods.Fusion/documentation/Fusion/FusionVersionNumber":{"kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"FusionVersionNumber"}],"type":"topic","title":"FusionVersionNumber","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/FusionVersionNumber","url":"\/documentation\/fusion\/fusionversionnumber","abstract":[]},"doc://org.cocoapods.Fusion/documentation/Fusion/Easing":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/Easing","navigatorTitle":[{"text":"Easing","kind":"identifier"}],"title":"Easing","abstract":[],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"Easing","kind":"identifier"}],"url":"\/documentation\/fusion\/easing"},"doc://org.cocoapods.Fusion/documentation/Fusion/UIKit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/UIKit","kind":"symbol","abstract":[],"url":"\/documentation\/fusion\/uikit","role":"collection","title":"UIKit"},"doc://org.cocoapods.Fusion/documentation/Fusion/ConfirmationCallback":{"role":"symbol","url":"\/documentation\/fusion\/confirmationcallback","navigatorTitle":[{"text":"ConfirmationCallback","kind":"identifier"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConfirmationCallback","kind":"identifier"}],"type":"topic","title":"ConfirmationCallback","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/ConfirmationCallback"},"doc://org.cocoapods.Fusion/documentation/Fusion/KeyPathName":{"title":"KeyPathName","url":"\/documentation\/fusion\/keypathname","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/KeyPathName","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyPathName","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"KeyPathName","kind":"identifier"}]},"doc://org.cocoapods.Fusion/documentation/Fusion/DataBindable":{"kind":"symbol","navigatorTitle":[{"text":"DataBindable","kind":"identifier"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DataBindable","kind":"identifier"}],"type":"topic","title":"DataBindable","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/DataBindable","url":"\/documentation\/fusion\/databindable","abstract":[{"text":"A protocol that provides reactive data binding capabilities with automatic lifecycle management.","type":"text"}]},"doc://org.cocoapods.Fusion/documentation/Fusion/RESTError":{"navigatorTitle":[{"text":"RESTError","kind":"identifier"}],"type":"topic","title":"RESTError","role":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/RESTError","url":"\/documentation\/fusion\/resterror","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RESTError"}]},"doc://org.cocoapods.Fusion/documentation/Fusion/TextUpdateModifier":{"url":"\/documentation\/fusion\/textupdatemodifier","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/TextUpdateModifier","navigatorTitle":[{"kind":"identifier","text":"TextUpdateModifier"}],"type":"topic","title":"TextUpdateModifier","abstract":[{"type":"text","text":"A view modifier that provides smooth animated transitions for text content."},{"type":"text","text":" "},{"type":"text","text":"This modifier automatically detects numeric values within text and animates them"},{"type":"text","text":" "},{"type":"text","text":"when the source text changes, creating smooth counting or value transition effects."},{"type":"text","text":" "},{"type":"text","text":"It preserves text formatting and attributes while animating only the numeric portions."}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TextUpdateModifier"}],"role":"symbol"},"doc://org.cocoapods.Fusion/documentation/Fusion/Logger":{"kind":"symbol","navigatorTitle":[{"text":"Logger","kind":"identifier"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Logger","kind":"identifier"}],"type":"topic","title":"Logger","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/Logger","url":"\/documentation\/fusion\/logger","abstract":[{"type":"text","text":"Logger is an enumeration that defines different logging levels."}]},"doc://org.cocoapods.Fusion/documentation/Fusion/syncMain(_:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/syncMain(_:)","kind":"symbol","abstract":[],"url":"\/documentation\/fusion\/syncmain(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"syncMain"},{"kind":"text","text":"(() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"title":"syncMain(_:)"},"doc://org.cocoapods.Fusion/documentation/Fusion/Keychain":{"navigatorTitle":[{"text":"Keychain","kind":"identifier"}],"title":"Keychain","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Keychain","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/fusion\/keychain","abstract":[{"text":"Keychain is a key-value storage. Each instance can be configured differently,","type":"text"},{"text":" ","type":"text"},{"text":"although the underlaying data persistence is the same. The Keychain store is attached to the","type":"text"},{"text":" ","type":"text"},{"text":"main bundle.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/Keychain"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":[{"generated":true,"title":"Classes","identifiers":["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/GradientView","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/RESTAuthenticator","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/UIHorizontalPanGestureRecognizer"],"anchor":"Classes"},{"generated":true,"title":"Variables","identifiers":["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/FusionVersionNumber","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/FusionVersionString","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/kFusionCoreName","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/kFusionCoreVersion","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/kFusionUIName","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/kFusionUIVersion"],"anchor":"Variables"}],"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":"GradientView","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1GradientView\/title"},{"op":"replace","value":[{"text":"GradientView","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1GradientView\/fragments"},{"op":"replace","value":[{"text":"GradientView","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1GradientView\/navigatorTitle"},{"op":"replace","value":"kFusionCoreVersion","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1kFusionCoreVersion\/title"},{"op":"replace","value":[{"text":"kFusionCoreVersion","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1kFusionCoreVersion\/fragments"},{"op":"replace","value":"UIHorizontalPanGestureRecognizer","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1UIHorizontalPanGestureRecognizer\/title"},{"op":"replace","value":[{"text":"UIHorizontalPanGestureRecognizer","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1UIHorizontalPanGestureRecognizer\/fragments"},{"op":"replace","value":[{"text":"UIHorizontalPanGestureRecognizer","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1UIHorizontalPanGestureRecognizer\/navigatorTitle"},{"op":"replace","value":"PresentationController","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController\/title"},{"op":"replace","value":[{"text":"PresentationController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController\/fragments"},{"op":"replace","value":[{"text":"PresentationController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController\/navigatorTitle"},{"op":"replace","value":"RESTAuthenticator","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1RESTAuthenticator\/title"},{"op":"replace","value":[{"text":"RESTAuthenticator","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1RESTAuthenticator\/fragments"},{"op":"replace","value":[{"text":"RESTAuthenticator","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1RESTAuthenticator\/navigatorTitle"},{"op":"replace","value":"kFusionUIVersion","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1kFusionUIVersion\/title"},{"op":"replace","value":[{"text":"kFusionUIVersion","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1kFusionUIVersion\/fragments"},{"op":"replace","value":"kFusionUIName","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1kFusionUIName\/title"},{"op":"replace","value":[{"text":"kFusionUIName","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1kFusionUIName\/fragments"},{"op":"replace","value":"AsyncOperation","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1AsyncOperation\/title"},{"op":"replace","value":[{"text":"AsyncOperation","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1AsyncOperation\/fragments"},{"op":"replace","value":[{"text":"AsyncOperation","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1AsyncOperation\/navigatorTitle"},{"op":"replace","value":"kFusionCoreName","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1kFusionCoreName\/title"},{"op":"replace","value":[{"text":"kFusionCoreName","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1kFusionCoreName\/fragments"}]}]}