{"abstract":[{"type":"text","text":"A subclass of "},{"type":"codeVoice","code":"Operation"},{"text":" that represents an asynchronous operation.","type":"text"}],"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AsyncOperation"}]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"inlineContent":[{"text":"This class is used to manage the state and execution of tasks that require asynchronous operations.","type":"text"}],"type":"paragraph"}]}],"metadata":{"symbolKind":"class","modules":[{"name":"Fusion"}],"title":"AsyncOperation","externalID":"c:@M@Fusion@objc(cs)AsyncOperation","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AsyncOperation"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AsyncOperation"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion"]]},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.Fusion\/objc(cs)NSOperation"],"type":"inheritsFrom"},{"title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.Fusion\/objc(pl)NSObject","doc:\/\/org.cocoapods.Fusion\/s7CVarArgP","doc:\/\/org.cocoapods.Fusion\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.Fusion\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.Fusion\/SQ","doc:\/\/org.cocoapods.Fusion\/SH","doc:\/\/org.cocoapods.Fusion\/s8SendableP","doc:\/\/org.cocoapods.Fusion\/s16SendableMetatypeP"],"type":"conformsTo","kind":"relationships"}],"identifier":{"url":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"anchor":"Initializers","title":"Initializers","generated":true,"identifiers":["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation\/init(task:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation\/isAsynchronous","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation\/isCancelled","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation\/isExecuting","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation\/isFinished","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation\/isReady","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation\/state-swift.property"],"anchor":"Instance-Properties","generated":true},{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation\/cancel()","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation\/complete()","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation\/start()"]},{"anchor":"Enumerations","title":"Enumerations","generated":true,"identifiers":["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation\/State-swift.enum"]}],"variants":[{"paths":["\/documentation\/fusion\/asyncoperation"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fusion\/asyncoperation"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.Fusion/s16SendableMetatypeP":{"title":"Swift.SendableMetatype","identifier":"doc:\/\/org.cocoapods.Fusion\/s16SendableMetatypeP","type":"unresolvable"},"doc://org.cocoapods.Fusion/documentation/Fusion/AsyncOperation/cancel()":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"cancel"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancel"},{"kind":"text","text":"()"}],"type":"topic","title":"cancel()","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation\/cancel()","url":"\/documentation\/fusion\/asyncoperation\/cancel()","abstract":[{"text":"Marks the operation as cancelled and sets its state to ","type":"text"},{"code":".cancelled","type":"codeVoice"},{"text":".","type":"text"}]},"doc://org.cocoapods.Fusion/documentation/Fusion":{"url":"\/documentation\/fusion","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion","type":"topic","title":"Fusion","abstract":[],"role":"collection"},"doc://org.cocoapods.Fusion/documentation/Fusion/AsyncOperation/state-swift.property":{"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"state"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:6Fusion14AsyncOperationC5StateO","text":"State"}],"type":"topic","title":"state","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation\/state-swift.property","url":"\/documentation\/fusion\/asyncoperation\/state-swift.property","abstract":[{"text":"The current state of the operation.","type":"text"}]},"doc://org.cocoapods.Fusion/documentation/Fusion/AsyncOperation/isFinished":{"title":"isFinished","url":"\/documentation\/fusion\/asyncoperation\/isfinished","abstract":[{"text":"Indicates whether the operation has finished execution.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation\/isFinished","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isFinished","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"finished","kind":"identifier"}]},"doc://org.cocoapods.Fusion/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.Fusion\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://org.cocoapods.Fusion/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Fusion\/s23CustomStringConvertibleP"},"doc://org.cocoapods.Fusion/documentation/Fusion/AsyncOperation/isAsynchronous":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"asynchronous"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation\/isAsynchronous","url":"\/documentation\/fusion\/asyncoperation\/isasynchronous","title":"isAsynchronous","abstract":[{"type":"text","text":"Indicates whether the operation is asynchronous."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isAsynchronous"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"doc://org.cocoapods.Fusion/documentation/Fusion/AsyncOperation/isReady":{"kind":"symbol","navigatorTitle":[{"text":"ready","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isReady","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"type":"topic","title":"isReady","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation\/isReady","url":"\/documentation\/fusion\/asyncoperation\/isready","abstract":[{"type":"text","text":"Indicates whether the operation is ready to start."}]},"doc://org.cocoapods.Fusion/SQ":{"identifier":"doc:\/\/org.cocoapods.Fusion\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://org.cocoapods.Fusion/documentation/Fusion/AsyncOperation/start()":{"kind":"symbol","title":"start()","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation\/start()","abstract":[{"text":"Starts the operation by setting its state to ","type":"text"},{"code":".executing","type":"codeVoice"},{"type":"text","text":" and executing the task."}],"role":"symbol","navigatorTitle":[{"text":"start","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"text":"()","kind":"text"}],"url":"\/documentation\/fusion\/asyncoperation\/start()","type":"topic"},"doc://org.cocoapods.Fusion/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Fusion\/SH"},"doc://org.cocoapods.Fusion/documentation/Fusion/AsyncOperation/isCancelled":{"kind":"symbol","title":"isCancelled","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation\/isCancelled","abstract":[{"text":"Indicates whether the operation has been cancelled.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"cancelled","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isCancelled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"url":"\/documentation\/fusion\/asyncoperation\/iscancelled","type":"topic"},"doc://org.cocoapods.Fusion/documentation/Fusion/AsyncOperation/State-swift.enum":{"navigatorTitle":[{"text":"State","kind":"identifier"}],"title":"AsyncOperation.State","type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"State","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/fusion\/asyncoperation\/state-swift.enum","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation\/State-swift.enum","abstract":[{"text":"An enumeration representing the state of an ","type":"text"},{"code":"AsyncOperation","type":"codeVoice"},{"text":".","type":"text"}]},"doc://org.cocoapods.Fusion/documentation/Fusion/AsyncOperation":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation","title":"AsyncOperation","abstract":[{"text":"A subclass of ","type":"text"},{"type":"codeVoice","code":"Operation"},{"text":" that represents an asynchronous operation.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"AsyncOperation","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AsyncOperation","kind":"identifier"}],"url":"\/documentation\/fusion\/asyncoperation","type":"topic"},"doc://org.cocoapods.Fusion/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Fusion\/s7CVarArgP"},"doc://org.cocoapods.Fusion/documentation/Fusion/AsyncOperation/complete()":{"kind":"symbol","title":"complete()","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation\/complete()","abstract":[{"text":"Marks the operation as completed and sets its state to ","type":"text"},{"type":"codeVoice","code":".finished"},{"text":".","type":"text"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"complete","kind":"identifier"},{"kind":"text","text":"()"}],"url":"\/documentation\/fusion\/asyncoperation\/complete()","type":"topic"},"doc://org.cocoapods.Fusion/documentation/Fusion/AsyncOperation/init(task:)":{"kind":"symbol","title":"init(task:)","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation\/init(task:)","abstract":[{"type":"text","text":"Initializes an "},{"type":"codeVoice","code":"AsyncOperation"},{"type":"text","text":" with a specified task closure."}],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"task","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:6Fusion9AsyncTaska","text":"AsyncTask","kind":"typeIdentifier"},{"kind":"text","text":")"}],"url":"\/documentation\/fusion\/asyncoperation\/init(task:)","type":"topic"},"doc://org.cocoapods.Fusion/objc(cs)NSOperation":{"title":"NSOperation","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Fusion\/objc(cs)NSOperation"},"doc://org.cocoapods.Fusion/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Fusion\/objc(pl)NSObject"},"doc://org.cocoapods.Fusion/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/org.cocoapods.Fusion\/s8SendableP"},"doc://org.cocoapods.Fusion/documentation/Fusion/AsyncOperation/isExecuting":{"kind":"symbol","navigatorTitle":[{"text":"executing","kind":"identifier"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isExecuting"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"type":"topic","title":"isExecuting","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation\/isExecuting","url":"\/documentation\/fusion\/asyncoperation\/isexecuting","abstract":[{"type":"text","text":"Indicates whether the operation is currently executing."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"AsyncOperation","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"AsyncOperation","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"AsyncOperation","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"anchor":"Instance-Properties","title":"Instance Properties","generated":true,"identifiers":["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation\/isAsynchronous","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation\/isCancelled","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation\/isExecuting","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation\/isFinished","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation\/isReady"]},{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation\/cancel()","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation\/start()"]}],"op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.Fusion\/objc(cs)NSOperation"],"type":"inheritsFrom"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AsyncOperation","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSOperation","preciseIdentifier":"c:objc(cs)NSOperation","kind":"typeIdentifier"}],"platforms":["iOS"]}]}},{"op":"replace","value":"cancel","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1AsyncOperation~1cancel()\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1AsyncOperation~1cancel()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"cancel"}]},{"op":"replace","value":"finished","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1AsyncOperation~1isFinished\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1AsyncOperation~1isFinished\/fragments","op":"replace","value":[{"kind":"identifier","text":"finished"}]},{"op":"replace","value":"asynchronous","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1AsyncOperation~1isAsynchronous\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1AsyncOperation~1isAsynchronous\/fragments","op":"replace","value":[{"text":"asynchronous","kind":"identifier"}]},{"op":"replace","value":"ready","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1AsyncOperation~1isReady\/title"},{"op":"replace","value":[{"text":"ready","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1AsyncOperation~1isReady\/fragments"},{"op":"replace","value":"start","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1AsyncOperation~1start()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"start","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1AsyncOperation~1start()\/fragments"},{"op":"replace","value":"cancelled","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1AsyncOperation~1isCancelled\/title"},{"op":"replace","value":[{"text":"cancelled","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1AsyncOperation~1isCancelled\/fragments"},{"op":"replace","value":"AsyncOperation","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1AsyncOperation\/title"},{"op":"replace","value":[{"text":"AsyncOperation","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1AsyncOperation\/fragments"},{"op":"replace","value":[{"text":"AsyncOperation","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1AsyncOperation\/navigatorTitle"},{"op":"replace","value":"executing","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1AsyncOperation~1isExecuting\/title"},{"op":"replace","value":[{"text":"executing","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1AsyncOperation~1isExecuting\/fragments"}]}]}