{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/kFusionUIVersion","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"kFusionUIVersion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/fusion\/kfusionuiversion"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fusion\/kfusionuiversion"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"text":"kFusionUIVersion","kind":"identifier"}],"title":"kFusionUIVersion","roleHeading":"Global Variable","symbolKind":"var","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"kFusionUIVersion"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"modules":[{"name":"Fusion"}],"externalID":"c:FusionUI.h@kFusionUIVersion","role":"symbol"},"references":{"doc://org.cocoapods.Fusion/documentation/Fusion":{"url":"\/documentation\/fusion","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion","type":"topic","title":"Fusion","abstract":[],"role":"collection"},"doc://org.cocoapods.Fusion/documentation/Fusion/kFusionUIVersion":{"kind":"symbol","navigatorTitle":[{"text":"kFusionUIVersion","kind":"identifier"}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kFusionUIVersion","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"type":"topic","title":"kFusionUIVersion","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/kFusionUIVersion","url":"\/documentation\/fusion\/kfusionuiversion","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Global Variable","path":"\/metadata\/roleHeading"},{"op":"replace","value":"kFusionUIVersion","path":"\/metadata\/title"},{"op":"replace","value":"var","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"kFusionUIVersion"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:d","text":"double"},{"kind":"text","text":" "},{"kind":"identifier","text":"kFusionUIVersion"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"kFusionUIVersion","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1kFusionUIVersion\/title"},{"op":"replace","value":[{"kind":"identifier","text":"kFusionUIVersion"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1kFusionUIVersion\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}