{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"transitionDuration"},{"kind":"text","text":"("},{"kind":"externalParam","text":"using"},{"kind":"text","text":" "},{"kind":"internalParam","text":"transitionContext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIViewControllerContextTransitioning","text":"UIViewControllerContextTransitioning"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"symbolKind":"method","modules":[{"name":"Fusion"}],"extendedModule":"Fusion","title":"transitionDuration(using:)","externalID":"c:@CM@Fusion@objc(cs)PresentationController(im)transitionDuration:","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transitionDuration","kind":"identifier"},{"text":"(","kind":"text"},{"text":"using","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIViewControllerContextTransitioning","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIViewControllerContextTransitioning"},{"text":"?) -> ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"}],"role":"symbol","navigatorTitle":[{"text":"transitionDuration:","kind":"identifier"}]},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/transitionDuration(using:)","interfaceLanguage":"swift"},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"UIViewControllerAnimatedTransitioning.transitionDuration(using:)","type":"codeVoice"},{"text":".","type":"text"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/fusion\/presentationcontroller\/transitionduration(using:)"]},{"paths":["\/documentation\/fusion\/presentationcontroller\/transitionduration(using:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.Fusion/documentation/Fusion":{"url":"\/documentation\/fusion","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion","type":"topic","title":"Fusion","abstract":[],"role":"collection"},"doc://org.cocoapods.Fusion/documentation/Fusion/PresentationController/transitionDuration(using:)":{"url":"\/documentation\/fusion\/presentationcontroller\/transitionduration(using:)","title":"transitionDuration(using:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"transitionDuration:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"transitionDuration"},{"kind":"text","text":"("},{"kind":"externalParam","text":"using"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIViewControllerContextTransitioning","text":"UIViewControllerContextTransitioning"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"}],"identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/transitionDuration(using:)","abstract":[],"role":"symbol","type":"topic"},"doc://org.cocoapods.Fusion/documentation/Fusion/PresentationController":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController","navigatorTitle":[{"kind":"identifier","text":"PresentationController"}],"title":"PresentationController","abstract":[{"type":"text","text":"A presentation controller that has a dimming view and presents from the bottom, as a drawer behavior."}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PresentationController"}],"url":"\/documentation\/fusion\/presentationcontroller"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"transitionDuration:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"transitionDuration:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"NSTimeInterval","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"transitionDuration:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qoobjc(pl)UIViewControllerContextTransitioning","text":"id<UIViewControllerContextTransitioning>","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"transitionContext","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController~1transitionDuration(using:)\/title","value":"transitionDuration:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController~1transitionDuration(using:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"transitionDuration:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController\/title","value":"PresentationController","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController\/fragments","value":[{"text":"PresentationController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController\/navigatorTitle","value":[{"text":"PresentationController","kind":"identifier"}],"op":"replace"}]}]}