{"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/animationController(forDismissed:)","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/animationController(forPresented:presenting:source:)","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/interactionControllerForDismissal(using:)","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/presentationController(forPresented:presenting:source:)"],"anchor":"Instance-Methods","generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/fusion\/presentationcontroller\/uiviewcontrollertransitioningdelegate-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/fusion\/presentationcontroller\/uiviewcontrollertransitioningdelegate-implementations"]}],"sections":[],"kind":"article","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController"]]},"identifier":{"url":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/UIViewControllerTransitioningDelegate-Implementations","interfaceLanguage":"swift"},"metadata":{"role":"collectionGroup","title":"UIViewControllerTransitioningDelegate Implementations","modules":[{"name":"Fusion"}],"roleHeading":"API Collection"},"references":{"doc://org.cocoapods.Fusion/documentation/Fusion/PresentationController/animationController(forDismissed:)":{"title":"animationController(forDismissed:)","url":"\/documentation\/fusion\/presentationcontroller\/animationcontroller(fordismissed:)","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/animationController(forDismissed:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"animationController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forDismissed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIViewControllerAnimatedTransitioning","text":"UIViewControllerAnimatedTransitioning"},{"kind":"text","text":"?"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"animationControllerForDismissedController:"}]},"doc://org.cocoapods.Fusion/documentation/Fusion":{"url":"\/documentation\/fusion","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion","type":"topic","title":"Fusion","abstract":[],"role":"collection"},"doc://org.cocoapods.Fusion/documentation/Fusion/PresentationController":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController","navigatorTitle":[{"kind":"identifier","text":"PresentationController"}],"title":"PresentationController","abstract":[{"type":"text","text":"A presentation controller that has a dimming view and presents from the bottom, as a drawer behavior."}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PresentationController"}],"url":"\/documentation\/fusion\/presentationcontroller"},"doc://org.cocoapods.Fusion/documentation/Fusion/PresentationController/interactionControllerForDismissal(using:)":{"title":"interactionControllerForDismissal(using:)","url":"\/documentation\/fusion\/presentationcontroller\/interactioncontrollerfordismissal(using:)","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/interactionControllerForDismissal(using:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"interactionControllerForDismissal"},{"kind":"text","text":"("},{"text":"using","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIViewControllerAnimatedTransitioning","text":"UIViewControllerAnimatedTransitioning"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(pl)UIViewControllerInteractiveTransitioning","text":"UIViewControllerInteractiveTransitioning","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"interactionControllerForDismissal:"}]},"doc://org.cocoapods.Fusion/documentation/Fusion/PresentationController/animationController(forPresented:presenting:source:)":{"kind":"symbol","navigatorTitle":[{"text":"animationControllerForPresentedController:presentingController:sourceController:","kind":"identifier"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"animationController","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forPresented"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"presenting"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"source","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"UIViewControllerAnimatedTransitioning","preciseIdentifier":"c:objc(pl)UIViewControllerAnimatedTransitioning","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","title":"animationController(forPresented:presenting:source:)","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/animationController(forPresented:presenting:source:)","url":"\/documentation\/fusion\/presentationcontroller\/animationcontroller(forpresented:presenting:source:)","abstract":[]},"doc://org.cocoapods.Fusion/documentation/Fusion/PresentationController/presentationController(forPresented:presenting:source:)":{"title":"presentationController(forPresented:presenting:source:)","url":"\/documentation\/fusion\/presentationcontroller\/presentationcontroller(forpresented:presenting:source:)","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/presentationController(forPresented:presenting:source:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"presentationController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forPresented","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"presenting","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"source","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"UIPresentationController","preciseIdentifier":"c:objc(cs)UIPresentationController","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"presentationControllerForPresentedViewController:presentingViewController:sourceViewController:","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":[{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/animationController(forDismissed:)","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/animationController(forPresented:presenting:source:)","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/interactionControllerForDismissal(using:)","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/presentationController(forPresented:presenting:source:)"]}],"path":"\/topicSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":"animationControllerForDismissedController:","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController~1animationController(forDismissed:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"animationControllerForDismissedController:"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController~1animationController(forDismissed:)\/fragments"},{"op":"replace","value":"PresentationController","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController\/title"},{"op":"replace","value":[{"kind":"identifier","text":"PresentationController"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"PresentationController"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController\/navigatorTitle"},{"op":"replace","value":"interactionControllerForDismissal:","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController~1interactionControllerForDismissal(using:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"interactionControllerForDismissal:"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController~1interactionControllerForDismissal(using:)\/fragments"},{"op":"replace","value":"animationControllerForPresentedController:presentingController:sourceController:","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController~1animationController(forPresented:presenting:source:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"animationControllerForPresentedController:presentingController:sourceController:"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController~1animationController(forPresented:presenting:source:)\/fragments"},{"op":"replace","value":"presentationControllerForPresentedViewController:presentingViewController:sourceViewController:","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController~1presentationController(forPresented:presenting:source:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"presentationControllerForPresentedViewController:presentingViewController:sourceViewController:"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController~1presentationController(forPresented:presenting:source:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}