{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation\/isExecuting"},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"modules":[{"name":"Fusion"}],"title":"isExecuting","role":"symbol","symbolKind":"property","navigatorTitle":[{"text":"executing","kind":"identifier"}],"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isExecuting","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"externalID":"c:@M@Fusion@objc(cs)AsyncOperation(py)executing"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isExecuting","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"abstract":[{"text":"Indicates whether the operation is currently executing.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/fusion\/asyncoperation\/isexecuting"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/fusion\/asyncoperation\/isexecuting"]}],"sections":[],"references":{"doc://org.cocoapods.Fusion/documentation/Fusion/AsyncOperation":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation","title":"AsyncOperation","abstract":[{"text":"A subclass of ","type":"text"},{"type":"codeVoice","code":"Operation"},{"text":" that represents an asynchronous operation.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"AsyncOperation","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AsyncOperation","kind":"identifier"}],"url":"\/documentation\/fusion\/asyncoperation","type":"topic"},"doc://org.cocoapods.Fusion/documentation/Fusion":{"url":"\/documentation\/fusion","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion","type":"topic","title":"Fusion","abstract":[],"role":"collection"},"doc://org.cocoapods.Fusion/documentation/Fusion/AsyncOperation/isExecuting":{"kind":"symbol","navigatorTitle":[{"text":"executing","kind":"identifier"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isExecuting"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"type":"topic","title":"isExecuting","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation\/isExecuting","url":"\/documentation\/fusion\/asyncoperation\/isexecuting","abstract":[{"type":"text","text":"Indicates whether the operation is currently executing."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"executing","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"executing","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":", ","kind":"text"},{"text":"getter","kind":"keyword"},{"text":"=","kind":"text"},{"text":"isExecuting","kind":"identifier"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"executing","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"AsyncOperation","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1AsyncOperation\/title"},{"op":"replace","value":[{"text":"AsyncOperation","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1AsyncOperation\/fragments"},{"op":"replace","value":[{"text":"AsyncOperation","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1AsyncOperation\/navigatorTitle"},{"op":"replace","value":"executing","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1AsyncOperation~1isExecuting\/title"},{"op":"replace","value":[{"text":"executing","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1AsyncOperation~1isExecuting\/fragments"}]}]}