{"abstract":[{"text":"Indicates whether the operation has finished execution.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/fusion\/asyncoperation\/isfinished"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/fusion\/asyncoperation\/isfinished"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"metadata":{"modules":[{"name":"Fusion"}],"symbolKind":"property","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isFinished"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"roleHeading":"Instance Property","externalID":"c:@M@Fusion@objc(cs)AsyncOperation(py)finished","title":"isFinished","navigatorTitle":[{"text":"finished","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isFinished"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation\/isFinished"},"kind":"symbol","references":{"doc://org.cocoapods.Fusion/documentation/Fusion/AsyncOperation/isFinished":{"title":"isFinished","url":"\/documentation\/fusion\/asyncoperation\/isfinished","abstract":[{"text":"Indicates whether the operation has finished execution.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation\/isFinished","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isFinished","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"finished","kind":"identifier"}]},"doc://org.cocoapods.Fusion/documentation/Fusion":{"url":"\/documentation\/fusion","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion","type":"topic","title":"Fusion","abstract":[],"role":"collection"},"doc://org.cocoapods.Fusion/documentation/Fusion/AsyncOperation":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation","title":"AsyncOperation","abstract":[{"text":"A subclass of ","type":"text"},{"type":"codeVoice","code":"Operation"},{"text":" that represents an asynchronous operation.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"AsyncOperation","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AsyncOperation","kind":"identifier"}],"url":"\/documentation\/fusion\/asyncoperation","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"finished","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"finished"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":", ","kind":"text"},{"text":"getter","kind":"keyword"},{"text":"=","kind":"text"},{"text":"isFinished","kind":"identifier"},{"text":") ","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"finished","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"finished","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1AsyncOperation~1isFinished\/title"},{"op":"replace","value":[{"kind":"identifier","text":"finished"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1AsyncOperation~1isFinished\/fragments"},{"op":"replace","value":"AsyncOperation","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1AsyncOperation\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AsyncOperation"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1AsyncOperation\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AsyncOperation"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1AsyncOperation\/navigatorTitle"}]}]}