{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation\/start()"},"metadata":{"symbolKind":"method","role":"symbol","externalID":"c:@M@Fusion@objc(cs)AsyncOperation(im)start","navigatorTitle":[{"kind":"identifier","text":"start"}],"modules":[{"name":"Fusion"}],"title":"start()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"start","kind":"identifier"},{"text":"()","kind":"text"}],"roleHeading":"Instance Method"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"()"}]}]}],"abstract":[{"type":"text","text":"Starts the operation by setting its state to "},{"code":".executing","type":"codeVoice"},{"type":"text","text":" and executing the task."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/fusion\/asyncoperation\/start()"]},{"paths":["\/documentation\/fusion\/asyncoperation\/start()"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://org.cocoapods.Fusion/documentation/Fusion":{"url":"\/documentation\/fusion","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion","type":"topic","title":"Fusion","abstract":[],"role":"collection"},"doc://org.cocoapods.Fusion/documentation/Fusion/AsyncOperation/start()":{"kind":"symbol","title":"start()","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation\/start()","abstract":[{"text":"Starts the operation by setting its state to ","type":"text"},{"code":".executing","type":"codeVoice"},{"type":"text","text":" and executing the task."}],"role":"symbol","navigatorTitle":[{"text":"start","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"text":"()","kind":"text"}],"url":"\/documentation\/fusion\/asyncoperation\/start()","type":"topic"},"doc://org.cocoapods.Fusion/documentation/Fusion/AsyncOperation":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation","title":"AsyncOperation","abstract":[{"text":"A subclass of ","type":"text"},{"type":"codeVoice","code":"Operation"},{"text":" that represents an asynchronous operation.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"AsyncOperation","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AsyncOperation","kind":"identifier"}],"url":"\/documentation\/fusion\/asyncoperation","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"start","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"start","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"start","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1AsyncOperation~1start()\/title","value":"start","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1AsyncOperation~1start()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"start","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1AsyncOperation\/title","value":"AsyncOperation","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1AsyncOperation\/fragments","value":[{"text":"AsyncOperation","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1AsyncOperation\/navigatorTitle","value":[{"text":"AsyncOperation","kind":"identifier"}],"op":"replace"}]}]}