{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"State"}]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"modules":[{"name":"Fusion"}],"title":"AsyncOperation.State","role":"symbol","symbolKind":"enum","navigatorTitle":[{"kind":"identifier","text":"State"}],"roleHeading":"Enumeration","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"State","kind":"identifier"}],"externalID":"s:6Fusion14AsyncOperationC5StateO"},"relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.Fusion\/SQ","doc:\/\/org.cocoapods.Fusion\/SH","doc:\/\/org.cocoapods.Fusion\/SY"],"kind":"relationships","type":"conformsTo"}],"kind":"symbol","topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation\/State-swift.enum\/cancelled","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation\/State-swift.enum\/executing","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation\/State-swift.enum\/finished","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation\/State-swift.enum\/ready"],"generated":true,"anchor":"Enumeration-Cases"},{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation\/State-swift.enum\/init(rawValue:)"],"generated":true,"anchor":"Initializers"},{"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation\/State-swift.enum\/Equatable-Implementations","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation\/State-swift.enum\/Hashable-Implementations","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation\/State-swift.enum\/RawRepresentable-Implementations"],"generated":true,"anchor":"Default-Implementations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation\/State-swift.enum"},"abstract":[{"type":"text","text":"An enumeration representing the state of an "},{"type":"codeVoice","code":"AsyncOperation"},{"type":"text","text":"."}],"sections":[],"variants":[{"paths":["\/documentation\/fusion\/asyncoperation\/state-swift.enum"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://org.cocoapods.Fusion/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.Fusion\/SH"},"doc://org.cocoapods.Fusion/documentation/Fusion/AsyncOperation/State-swift.enum/RawRepresentable-Implementations":{"url":"\/documentation\/fusion\/asyncoperation\/state-swift.enum\/rawrepresentable-implementations","role":"collectionGroup","kind":"article","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation\/State-swift.enum\/RawRepresentable-Implementations","type":"topic","title":"RawRepresentable Implementations","abstract":[]},"doc://org.cocoapods.Fusion/documentation/Fusion/AsyncOperation/State-swift.enum":{"navigatorTitle":[{"text":"State","kind":"identifier"}],"title":"AsyncOperation.State","type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"State","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/fusion\/asyncoperation\/state-swift.enum","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation\/State-swift.enum","abstract":[{"text":"An enumeration representing the state of an ","type":"text"},{"code":"AsyncOperation","type":"codeVoice"},{"text":".","type":"text"}]},"doc://org.cocoapods.Fusion/documentation/Fusion/AsyncOperation":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation","title":"AsyncOperation","abstract":[{"text":"A subclass of ","type":"text"},{"type":"codeVoice","code":"Operation"},{"text":" that represents an asynchronous operation.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"AsyncOperation","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AsyncOperation","kind":"identifier"}],"url":"\/documentation\/fusion\/asyncoperation","type":"topic"},"doc://org.cocoapods.Fusion/documentation/Fusion/AsyncOperation/State-swift.enum/Hashable-Implementations":{"url":"\/documentation\/fusion\/asyncoperation\/state-swift.enum\/hashable-implementations","role":"collectionGroup","kind":"article","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation\/State-swift.enum\/Hashable-Implementations","type":"topic","title":"Hashable Implementations","abstract":[]},"doc://org.cocoapods.Fusion/documentation/Fusion/AsyncOperation/State-swift.enum/Equatable-Implementations":{"url":"\/documentation\/fusion\/asyncoperation\/state-swift.enum\/equatable-implementations","role":"collectionGroup","kind":"article","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation\/State-swift.enum\/Equatable-Implementations","type":"topic","title":"Equatable Implementations","abstract":[]},"doc://org.cocoapods.Fusion/documentation/Fusion/AsyncOperation/State-swift.enum/executing":{"url":"\/documentation\/fusion\/asyncoperation\/state-swift.enum\/executing","title":"AsyncOperation.State.executing","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"executing"}],"identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation\/State-swift.enum\/executing","abstract":[],"role":"symbol","type":"topic"},"doc://org.cocoapods.Fusion/documentation/Fusion":{"url":"\/documentation\/fusion","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion","type":"topic","title":"Fusion","abstract":[],"role":"collection"},"doc://org.cocoapods.Fusion/documentation/Fusion/AsyncOperation/State-swift.enum/ready":{"url":"\/documentation\/fusion\/asyncoperation\/state-swift.enum\/ready","title":"AsyncOperation.State.ready","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ready"}],"identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation\/State-swift.enum\/ready","abstract":[],"role":"symbol","type":"topic"},"doc://org.cocoapods.Fusion/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.Fusion\/SQ","type":"unresolvable"},"doc://org.cocoapods.Fusion/SY":{"title":"Swift.RawRepresentable","identifier":"doc:\/\/org.cocoapods.Fusion\/SY","type":"unresolvable"},"doc://org.cocoapods.Fusion/documentation/Fusion/AsyncOperation/State-swift.enum/init(rawValue:)":{"url":"\/documentation\/fusion\/asyncoperation\/state-swift.enum\/init(rawvalue:)","role":"symbol","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation\/State-swift.enum\/init(rawValue:)","type":"topic","title":"init(rawValue:)","abstract":[]},"doc://org.cocoapods.Fusion/documentation/Fusion/AsyncOperation/State-swift.enum/cancelled":{"title":"AsyncOperation.State.cancelled","url":"\/documentation\/fusion\/asyncoperation\/state-swift.enum\/cancelled","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation\/State-swift.enum\/cancelled","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelled"}],"type":"topic","role":"symbol"},"doc://org.cocoapods.Fusion/documentation/Fusion/AsyncOperation/State-swift.enum/finished":{"type":"topic","title":"AsyncOperation.State.finished","role":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/AsyncOperation\/State-swift.enum\/finished","url":"\/documentation\/fusion\/asyncoperation\/state-swift.enum\/finished","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"finished"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1AsyncOperation\/title","value":"AsyncOperation"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1AsyncOperation\/fragments","value":[{"text":"AsyncOperation","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1AsyncOperation\/navigatorTitle","value":[{"text":"AsyncOperation","kind":"identifier"}]}]}]}