{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/RESTAuthenticator"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/RESTAuthenticator\/hashKeys","interfaceLanguage":"swift"},"metadata":{"externalID":"s:6Fusion17RESTAuthenticatorC8hashKeysSaySSGvp","modules":[{"name":"Fusion"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hashKeys"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]"}],"roleHeading":"Instance Property","symbolKind":"property","role":"symbol","title":"hashKeys"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hashKeys"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"]"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/fusion\/restauthenticator\/hashkeys"]}],"sections":[],"references":{"doc://org.cocoapods.Fusion/documentation/Fusion":{"url":"\/documentation\/fusion","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion","type":"topic","title":"Fusion","abstract":[],"role":"collection"},"doc://org.cocoapods.Fusion/documentation/Fusion/RESTAuthenticator":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"RESTAuthenticator","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/RESTAuthenticator","url":"\/documentation\/fusion\/restauthenticator","title":"RESTAuthenticator","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RESTAuthenticator","kind":"identifier"}]},"doc://org.cocoapods.Fusion/documentation/Fusion/RESTAuthenticator/hashKeys":{"url":"\/documentation\/fusion\/restauthenticator\/hashkeys","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hashKeys"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"]"}],"identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/RESTAuthenticator\/hashKeys","type":"topic","title":"hashKeys","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","value":"RESTAuthenticator","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1RESTAuthenticator\/title"},{"value":[{"text":"RESTAuthenticator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1RESTAuthenticator\/fragments"},{"value":[{"text":"RESTAuthenticator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1RESTAuthenticator\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}