{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"},{"text":"()","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/GradientView"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"navigatorTitle":[{"text":"layoutSubviews","kind":"identifier"}],"title":"layoutSubviews()","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"},{"text":"()","kind":"text"}],"roleHeading":"Instance Method","modules":[{"name":"Fusion"}],"externalID":"c:@M@Fusion@objc(cs)GradientView(im)layoutSubviews","symbolKind":"method"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/GradientView\/layoutSubviews()"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/fusion\/gradientview\/layoutsubviews()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/fusion\/gradientview\/layoutsubviews()"]}],"sections":[],"references":{"doc://org.cocoapods.Fusion/documentation/Fusion":{"url":"\/documentation\/fusion","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion","type":"topic","title":"Fusion","abstract":[],"role":"collection"},"doc://org.cocoapods.Fusion/documentation/Fusion/GradientView":{"title":"GradientView","url":"\/documentation\/fusion\/gradientview","abstract":[{"text":"Convenience view that encpsulates the ","type":"text"},{"code":"UIView.make(gradient:start:end:type:)","type":"codeVoice"},{"text":" and makes it automatically redrawable and adaptable.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/GradientView","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GradientView"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GradientView"}]},"doc://org.cocoapods.Fusion/documentation/Fusion/GradientView/layoutSubviews()":{"url":"\/documentation\/fusion\/gradientview\/layoutsubviews()","title":"layoutSubviews()","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"layoutSubviews"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutSubviews"},{"kind":"text","text":"()"}],"identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/GradientView\/layoutSubviews()","abstract":[],"role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"layoutSubviews","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layoutSubviews"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"GradientView","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1GradientView\/title"},{"op":"replace","value":[{"kind":"identifier","text":"GradientView"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1GradientView\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"GradientView"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1GradientView\/navigatorTitle"},{"op":"replace","value":"layoutSubviews","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1GradientView~1layoutSubviews()\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layoutSubviews"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1GradientView~1layoutSubviews()\/fragments"}]}]}