{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/fusion\/gradientview\/start"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"modules":[{"name":"Fusion"}],"symbolKind":"property","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint","text":"CGPoint"}],"roleHeading":"Instance Property","externalID":"s:6Fusion12GradientViewC5startSo7CGPointVvp","title":"start"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGPoint","preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/GradientView"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/GradientView\/start"},"sections":[],"references":{"doc://org.cocoapods.Fusion/documentation/Fusion":{"url":"\/documentation\/fusion","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion","type":"topic","title":"Fusion","abstract":[],"role":"collection"},"doc://org.cocoapods.Fusion/documentation/Fusion/GradientView":{"title":"GradientView","url":"\/documentation\/fusion\/gradientview","abstract":[{"text":"Convenience view that encpsulates the ","type":"text"},{"code":"UIView.make(gradient:start:end:type:)","type":"codeVoice"},{"text":" and makes it automatically redrawable and adaptable.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/GradientView","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GradientView"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GradientView"}]},"doc://org.cocoapods.Fusion/documentation/Fusion/GradientView/start":{"title":"start","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"start","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint","text":"CGPoint"}],"kind":"symbol","url":"\/documentation\/fusion\/gradientview\/start","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/GradientView\/start","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","value":"GradientView","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1GradientView\/title"},{"op":"replace","value":[{"text":"GradientView","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1GradientView\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1GradientView\/navigatorTitle","op":"replace","value":[{"text":"GradientView","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}