{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/GradientView\/type"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/fusion\/gradientview\/type"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/GradientView"]]},"metadata":{"title":"type","roleHeading":"Instance Property","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CAGradientLayerType","preciseIdentifier":"c:@T@CAGradientLayerType"}],"externalID":"s:6Fusion12GradientViewC4typeSo19CAGradientLayerTypeavp","modules":[{"name":"Fusion"}],"role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@CAGradientLayerType","text":"CAGradientLayerType","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://org.cocoapods.Fusion/documentation/Fusion/GradientView/type":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/GradientView\/type","title":"type","abstract":[],"kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CAGradientLayerType","kind":"typeIdentifier","preciseIdentifier":"c:@T@CAGradientLayerType"}],"url":"\/documentation\/fusion\/gradientview\/type"},"doc://org.cocoapods.Fusion/documentation/Fusion":{"url":"\/documentation\/fusion","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion","type":"topic","title":"Fusion","abstract":[],"role":"collection"},"doc://org.cocoapods.Fusion/documentation/Fusion/GradientView":{"title":"GradientView","url":"\/documentation\/fusion\/gradientview","abstract":[{"text":"Convenience view that encpsulates the ","type":"text"},{"code":"UIView.make(gradient:start:end:type:)","type":"codeVoice"},{"text":" and makes it automatically redrawable and adaptable.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/GradientView","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GradientView"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GradientView"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"GradientView","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1GradientView\/title"},{"op":"replace","value":[{"kind":"identifier","text":"GradientView"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1GradientView\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"GradientView"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1GradientView\/navigatorTitle"}]}]}