{"abstract":[{"type":"text","text":"Inherited from "},{"code":"UIViewControllerTransitioningDelegate.animationController(forDismissed:)","type":"codeVoice"},{"type":"text","text":"."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/fusion\/presentationcontroller\/animationcontroller(fordismissed:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/fusion\/presentationcontroller\/animationcontroller(fordismissed:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"animationControllerForDismissedController:"}],"title":"animationController(forDismissed:)","role":"symbol","extendedModule":"Fusion","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"animationController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forDismissed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIViewControllerAnimatedTransitioning","preciseIdentifier":"c:objc(pl)UIViewControllerAnimatedTransitioning"},{"kind":"text","text":"?"}],"modules":[{"name":"Fusion"}],"externalID":"c:@CM@Fusion@objc(cs)PresentationController(im)animationControllerForDismissedController:","symbolKind":"method"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"animationController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forDismissed"},{"kind":"text","text":" "},{"kind":"internalParam","text":"dismissed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIViewControllerAnimatedTransitioning","preciseIdentifier":"c:objc(pl)UIViewControllerAnimatedTransitioning"},{"kind":"text","text":"?"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/animationController(forDismissed:)"},"sections":[],"references":{"doc://org.cocoapods.Fusion/documentation/Fusion/PresentationController/animationController(forDismissed:)":{"title":"animationController(forDismissed:)","url":"\/documentation\/fusion\/presentationcontroller\/animationcontroller(fordismissed:)","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/animationController(forDismissed:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"animationController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forDismissed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIViewControllerAnimatedTransitioning","text":"UIViewControllerAnimatedTransitioning"},{"kind":"text","text":"?"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"animationControllerForDismissedController:"}]},"doc://org.cocoapods.Fusion/documentation/Fusion/PresentationController":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController","navigatorTitle":[{"kind":"identifier","text":"PresentationController"}],"title":"PresentationController","abstract":[{"type":"text","text":"A presentation controller that has a dimming view and presents from the bottom, as a drawer behavior."}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PresentationController"}],"url":"\/documentation\/fusion\/presentationcontroller"},"doc://org.cocoapods.Fusion/documentation/Fusion":{"url":"\/documentation\/fusion","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion","type":"topic","title":"Fusion","abstract":[],"role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"animationControllerForDismissedController:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"animationControllerForDismissedController:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id<UIViewControllerAnimatedTransitioning>","preciseIdentifier":"c:Qoobjc(pl)UIViewControllerAnimatedTransitioning","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"animationControllerForDismissedController:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"dismissed","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"animationControllerForDismissedController:","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController~1animationController(forDismissed:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"animationControllerForDismissedController:"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController~1animationController(forDismissed:)\/fragments"},{"op":"replace","value":"PresentationController","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController\/title"},{"op":"replace","value":[{"kind":"identifier","text":"PresentationController"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"PresentationController"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController\/navigatorTitle"}]}]}