{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/cornerRadius","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Property","externalID":"s:6Fusion22PresentationControllerC12cornerRadiusAA11RectCornersVvp","symbolKind":"property","modules":[{"name":"Fusion"}],"title":"cornerRadius","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cornerRadius","kind":"identifier"},{"text":": ","kind":"text"},{"text":"RectCorners","kind":"typeIdentifier","preciseIdentifier":"s:6Fusion11RectCornersV"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController"]]},"abstract":[{"text":"The corner radius of the drawer frame.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cornerRadius","kind":"identifier"},{"text":": ","kind":"text"},{"text":"RectCorners","kind":"typeIdentifier","preciseIdentifier":"s:6Fusion11RectCornersV","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/RectCorners"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/fusion\/presentationcontroller\/cornerradius"]}],"sections":[],"references":{"doc://org.cocoapods.Fusion/documentation/Fusion/PresentationController":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController","navigatorTitle":[{"kind":"identifier","text":"PresentationController"}],"title":"PresentationController","abstract":[{"type":"text","text":"A presentation controller that has a dimming view and presents from the bottom, as a drawer behavior."}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PresentationController"}],"url":"\/documentation\/fusion\/presentationcontroller"},"doc://org.cocoapods.Fusion/documentation/Fusion":{"url":"\/documentation\/fusion","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion","type":"topic","title":"Fusion","abstract":[],"role":"collection"},"doc://org.cocoapods.Fusion/documentation/Fusion/PresentationController/cornerRadius":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cornerRadius","kind":"identifier"},{"text":": ","kind":"text"},{"text":"RectCorners","preciseIdentifier":"s:6Fusion11RectCornersV","kind":"typeIdentifier"}],"title":"cornerRadius","role":"symbol","abstract":[{"text":"The corner radius of the drawer frame.","type":"text"}],"url":"\/documentation\/fusion\/presentationcontroller\/cornerradius","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/cornerRadius","kind":"symbol"},"doc://org.cocoapods.Fusion/documentation/Fusion/RectCorners":{"type":"topic","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/RectCorners","kind":"symbol","abstract":[{"text":"Represents the corner radii of a rectangle with individual values for each corner.","type":"text"}],"url":"\/documentation\/fusion\/rectcorners","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"RectCorners"}],"navigatorTitle":[{"kind":"identifier","text":"RectCorners"}],"title":"RectCorners"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController\/title","value":"PresentationController","op":"replace"},{"value":[{"text":"PresentationController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController\/fragments","op":"replace"},{"value":[{"text":"PresentationController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController\/navigatorTitle"}]}]}