{"abstract":[{"type":"text","text":"Inherited from "},{"code":"UIViewControllerAnimatedTransitioning.interruptibleAnimator(using:)","type":"codeVoice"},{"type":"text","text":"."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/fusion\/presentationcontroller\/interruptibleanimator(using:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/fusion\/presentationcontroller\/interruptibleanimator(using:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"symbolKind":"method","role":"symbol","externalID":"c:@CM@Fusion@objc(cs)PresentationController(im)interruptibleAnimatorForTransition:","navigatorTitle":[{"kind":"identifier","text":"interruptibleAnimatorForTransition:"}],"modules":[{"name":"Fusion"}],"extendedModule":"Fusion","title":"interruptibleAnimator(using:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"interruptibleAnimator","kind":"identifier"},{"kind":"text","text":"("},{"text":"using","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(pl)UIViewControllerContextTransitioning","kind":"typeIdentifier","text":"UIViewControllerContextTransitioning"},{"kind":"text","text":") -> "},{"text":"UIViewImplicitlyAnimating","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIViewImplicitlyAnimating"}],"roleHeading":"Instance Method"},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"interruptibleAnimator"},{"kind":"text","text":"("},{"kind":"externalParam","text":"using"},{"kind":"text","text":" "},{"kind":"internalParam","text":"transitionContext"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(pl)UIViewControllerContextTransitioning","kind":"typeIdentifier","text":"UIViewControllerContextTransitioning"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(pl)UIViewImplicitlyAnimating","kind":"typeIdentifier","text":"UIViewImplicitlyAnimating"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/interruptibleAnimator(using:)"},"sections":[],"references":{"doc://org.cocoapods.Fusion/documentation/Fusion/PresentationController/interruptibleAnimator(using:)":{"abstract":[],"navigatorTitle":[{"text":"interruptibleAnimatorForTransition:","kind":"identifier"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"interruptibleAnimator","kind":"identifier"},{"text":"(","kind":"text"},{"text":"using","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(pl)UIViewControllerContextTransitioning","text":"UIViewControllerContextTransitioning","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(pl)UIViewImplicitlyAnimating","text":"UIViewImplicitlyAnimating","kind":"typeIdentifier"}],"type":"topic","title":"interruptibleAnimator(using:)","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/interruptibleAnimator(using:)","url":"\/documentation\/fusion\/presentationcontroller\/interruptibleanimator(using:)","kind":"symbol"},"doc://org.cocoapods.Fusion/documentation/Fusion":{"url":"\/documentation\/fusion","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion","type":"topic","title":"Fusion","abstract":[],"role":"collection"},"doc://org.cocoapods.Fusion/documentation/Fusion/PresentationController":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController","navigatorTitle":[{"kind":"identifier","text":"PresentationController"}],"title":"PresentationController","abstract":[{"type":"text","text":"A presentation controller that has a dimming view and presents from the bottom, as a drawer behavior."}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PresentationController"}],"url":"\/documentation\/fusion\/presentationcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"interruptibleAnimatorForTransition:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"interruptibleAnimatorForTransition:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id<UIViewImplicitlyAnimating>","preciseIdentifier":"c:Qoobjc(pl)UIViewImplicitlyAnimating"},{"kind":"text","text":") "},{"kind":"identifier","text":"interruptibleAnimatorForTransition:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<UIViewControllerContextTransitioning>","preciseIdentifier":"c:Qoobjc(pl)UIViewControllerContextTransitioning"},{"kind":"text","text":") "},{"kind":"internalParam","text":"transitionContext"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"interruptibleAnimatorForTransition:","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController~1interruptibleAnimator(using:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"interruptibleAnimatorForTransition:"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController~1interruptibleAnimator(using:)\/fragments"},{"op":"replace","value":"PresentationController","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController\/title"},{"op":"replace","value":[{"kind":"identifier","text":"PresentationController"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"PresentationController"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}