{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"picInPic","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"picInPic","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"externalID":"s:6Fusion22PresentationControllerC8picInPicSbvp","modules":[{"name":"Fusion"}],"title":"picInPic","symbolKind":"property","role":"symbol"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/fusion\/presentationcontroller\/picinpic"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController"]]},"kind":"symbol","abstract":[{"type":"text","text":"Keeps the previous View Controller visible on top, the return navigation is done by tapping on it."}],"identifier":{"url":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/picInPic","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.Fusion/documentation/Fusion":{"url":"\/documentation\/fusion","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion","type":"topic","title":"Fusion","abstract":[],"role":"collection"},"doc://org.cocoapods.Fusion/documentation/Fusion/PresentationController/picInPic":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"picInPic"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic","title":"picInPic","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/picInPic","url":"\/documentation\/fusion\/presentationcontroller\/picinpic","abstract":[{"type":"text","text":"Keeps the previous View Controller visible on top, the return navigation is done by tapping on it."}]},"doc://org.cocoapods.Fusion/documentation/Fusion/PresentationController":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController","navigatorTitle":[{"kind":"identifier","text":"PresentationController"}],"title":"PresentationController","abstract":[{"type":"text","text":"A presentation controller that has a dimming view and presents from the bottom, as a drawer behavior."}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PresentationController"}],"url":"\/documentation\/fusion\/presentationcontroller"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController\/title","value":"PresentationController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController\/fragments","value":[{"text":"PresentationController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController\/navigatorTitle","value":[{"kind":"identifier","text":"PresentationController"}]}]}]}