{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController"]]},"metadata":{"symbolKind":"method","modules":[{"name":"Fusion"}],"roleHeading":"Instance Method","externalID":"c:@M@Fusion@objc(cs)PresentationController(im)preferredContentSizeDidChangeForChildContentContainer:","title":"preferredContentSizeDidChange(forChildContentContainer:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferredContentSizeDidChange"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forChildContentContainer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIContentContainer","preciseIdentifier":"c:objc(pl)UIContentContainer"},{"kind":"text","text":")"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"preferredContentSizeDidChangeForChildContentContainer:"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/fusion\/presentationcontroller\/preferredcontentsizedidchange(forchildcontentcontainer:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/fusion\/presentationcontroller\/preferredcontentsizedidchange(forchildcontentcontainer:)"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/preferredContentSizeDidChange(forChildContentContainer:)"},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferredContentSizeDidChange"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forChildContentContainer"},{"kind":"text","text":" "},{"kind":"internalParam","text":"container"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIContentContainer","text":"UIContentContainer"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"references":{"doc://org.cocoapods.Fusion/documentation/Fusion":{"url":"\/documentation\/fusion","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion","type":"topic","title":"Fusion","abstract":[],"role":"collection"},"doc://org.cocoapods.Fusion/documentation/Fusion/PresentationController":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController","navigatorTitle":[{"kind":"identifier","text":"PresentationController"}],"title":"PresentationController","abstract":[{"type":"text","text":"A presentation controller that has a dimming view and presents from the bottom, as a drawer behavior."}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PresentationController"}],"url":"\/documentation\/fusion\/presentationcontroller"},"doc://org.cocoapods.Fusion/documentation/Fusion/PresentationController/preferredContentSizeDidChange(forChildContentContainer:)":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"preferredContentSizeDidChangeForChildContentContainer:"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferredContentSizeDidChange"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forChildContentContainer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIContentContainer","text":"UIContentContainer"},{"kind":"text","text":")"}],"type":"topic","title":"preferredContentSizeDidChange(forChildContentContainer:)","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/preferredContentSizeDidChange(forChildContentContainer:)","url":"\/documentation\/fusion\/presentationcontroller\/preferredcontentsizedidchange(forchildcontentcontainer:)","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"preferredContentSizeDidChangeForChildContentContainer:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"preferredContentSizeDidChangeForChildContentContainer:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"preferredContentSizeDidChangeForChildContentContainer:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)UIContentContainer","text":"id<UIContentContainer>"},{"kind":"text","text":") "},{"kind":"internalParam","text":"container"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController\/title","value":"PresentationController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController\/fragments","value":[{"kind":"identifier","text":"PresentationController"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController\/navigatorTitle","value":[{"kind":"identifier","text":"PresentationController"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController~1preferredContentSizeDidChange(forChildContentContainer:)\/title","value":"preferredContentSizeDidChangeForChildContentContainer:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController~1preferredContentSizeDidChange(forChildContentContainer:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"preferredContentSizeDidChangeForChildContentContainer:"}]}]}]}