{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentationController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forPresented"},{"kind":"text","text":" "},{"kind":"internalParam","text":"presented"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"presenting"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"source"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIPresentationController","preciseIdentifier":"c:objc(cs)UIPresentationController"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UIViewControllerTransitioningDelegate.presentationController(forPresented:presenting:source:)"},{"type":"text","text":"."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/fusion\/presentationcontroller\/presentationcontroller(forpresented:presenting:source:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/fusion\/presentationcontroller\/presentationcontroller(forpresented:presenting:source:)"]}],"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/presentationController(forPresented:presenting:source:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController"]]},"metadata":{"title":"presentationController(forPresented:presenting:source:)","roleHeading":"Instance Method","modules":[{"name":"Fusion"}],"extendedModule":"Fusion","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentationController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forPresented"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"presenting"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"source"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)UIPresentationController","kind":"typeIdentifier","text":"UIPresentationController"},{"kind":"text","text":"?"}],"externalID":"c:@CM@Fusion@objc(cs)PresentationController(im)presentationControllerForPresentedViewController:presentingViewController:sourceViewController:","role":"symbol","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"presentationControllerForPresentedViewController:presentingViewController:sourceViewController:"}]},"references":{"doc://org.cocoapods.Fusion/documentation/Fusion/PresentationController":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController","navigatorTitle":[{"kind":"identifier","text":"PresentationController"}],"title":"PresentationController","abstract":[{"type":"text","text":"A presentation controller that has a dimming view and presents from the bottom, as a drawer behavior."}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PresentationController"}],"url":"\/documentation\/fusion\/presentationcontroller"},"doc://org.cocoapods.Fusion/documentation/Fusion/PresentationController/presentationController(forPresented:presenting:source:)":{"title":"presentationController(forPresented:presenting:source:)","url":"\/documentation\/fusion\/presentationcontroller\/presentationcontroller(forpresented:presenting:source:)","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/presentationController(forPresented:presenting:source:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"presentationController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forPresented","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"presenting","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"source","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"UIPresentationController","preciseIdentifier":"c:objc(cs)UIPresentationController","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"presentationControllerForPresentedViewController:presentingViewController:sourceViewController:","kind":"identifier"}]},"doc://org.cocoapods.Fusion/documentation/Fusion":{"url":"\/documentation\/fusion","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion","type":"topic","title":"Fusion","abstract":[],"role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"presentationControllerForPresentedViewController:presentingViewController:sourceViewController:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"presentationControllerForPresentedViewController:presentingViewController:sourceViewController:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"UIPresentationController","preciseIdentifier":"c:objc(cs)UIPresentationController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"presentationControllerForPresentedViewController:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"presented","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"presentingViewController:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"presenting","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"sourceViewController:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"source","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController\/title","value":"PresentationController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController\/fragments","value":[{"kind":"identifier","text":"PresentationController"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController\/navigatorTitle","value":[{"kind":"identifier","text":"PresentationController"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController~1presentationController(forPresented:presenting:source:)\/title","value":"presentationControllerForPresentedViewController:presentingViewController:sourceViewController:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController~1presentationController(forPresented:presenting:source:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"presentationControllerForPresentedViewController:presentingViewController:sourceViewController:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}