{"identifier":{"url":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/presentingSide","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/fusion\/presentationcontroller\/presentingside"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"type":"text","text":"Defines the presenting side of the new controller."}],"metadata":{"title":"presentingSide","roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"presentingSide","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIRectEdge","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIRectEdge"}],"modules":[{"name":"Fusion"}],"externalID":"s:6Fusion22PresentationControllerC14presentingSideSo10UIRectEdgeVvp","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"presentingSide","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIRectEdge","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIRectEdge"}]}]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://org.cocoapods.Fusion/documentation/Fusion/PresentationController/presentingSide":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/presentingSide","title":"presentingSide","abstract":[{"type":"text","text":"Defines the presenting side of the new controller."}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentingSide"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@UIRectEdge","kind":"typeIdentifier","text":"UIRectEdge"}],"url":"\/documentation\/fusion\/presentationcontroller\/presentingside"},"doc://org.cocoapods.Fusion/documentation/Fusion/PresentationController":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController","navigatorTitle":[{"kind":"identifier","text":"PresentationController"}],"title":"PresentationController","abstract":[{"type":"text","text":"A presentation controller that has a dimming view and presents from the bottom, as a drawer behavior."}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PresentationController"}],"url":"\/documentation\/fusion\/presentationcontroller"},"doc://org.cocoapods.Fusion/documentation/Fusion":{"url":"\/documentation\/fusion","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion","type":"topic","title":"Fusion","abstract":[],"role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController\/title","value":"PresentationController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController\/fragments","value":[{"text":"PresentationController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController\/navigatorTitle","value":[{"text":"PresentationController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}