{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentationTransitionWillBegin"},{"kind":"text","text":"()"}]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"symbolKind":"method","modules":[{"name":"Fusion"}],"title":"presentationTransitionWillBegin()","roleHeading":"Instance Method","externalID":"c:@M@Fusion@objc(cs)PresentationController(im)presentationTransitionWillBegin","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"presentationTransitionWillBegin","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"presentationTransitionWillBegin","kind":"identifier"}]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/presentationTransitionWillBegin()"},"variants":[{"paths":["\/documentation\/fusion\/presentationcontroller\/presentationtransitionwillbegin()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fusion\/presentationcontroller\/presentationtransitionwillbegin()"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://org.cocoapods.Fusion/documentation/Fusion/PresentationController/presentationTransitionWillBegin()":{"url":"\/documentation\/fusion\/presentationcontroller\/presentationtransitionwillbegin()","title":"presentationTransitionWillBegin()","kind":"symbol","navigatorTitle":[{"text":"presentationTransitionWillBegin","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"presentationTransitionWillBegin","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/presentationTransitionWillBegin()","abstract":[],"role":"symbol","type":"topic"},"doc://org.cocoapods.Fusion/documentation/Fusion/PresentationController":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController","navigatorTitle":[{"kind":"identifier","text":"PresentationController"}],"title":"PresentationController","abstract":[{"type":"text","text":"A presentation controller that has a dimming view and presents from the bottom, as a drawer behavior."}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PresentationController"}],"url":"\/documentation\/fusion\/presentationcontroller"},"doc://org.cocoapods.Fusion/documentation/Fusion":{"url":"\/documentation\/fusion","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion","type":"topic","title":"Fusion","abstract":[],"role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"presentationTransitionWillBegin","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"presentationTransitionWillBegin","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"presentationTransitionWillBegin"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"presentationTransitionWillBegin","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController~1presentationTransitionWillBegin()\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"presentationTransitionWillBegin","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController~1presentationTransitionWillBegin()\/fragments"},{"value":"PresentationController","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController\/title"},{"value":[{"text":"PresentationController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController\/fragments"},{"value":[{"text":"PresentationController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController\/navigatorTitle"}]}]}