{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"role":"collectionGroup","title":"UIViewControllerAnimatedTransitioning Implementations","modules":[{"name":"Fusion"}],"roleHeading":"API Collection"},"kind":"article","topicSections":[{"title":"Instance Methods","anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/animateTransition(using:)","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/interruptibleAnimator(using:)","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/transitionDuration(using:)"]}],"identifier":{"url":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/UIViewControllerAnimatedTransitioning-Implementations","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/fusion\/presentationcontroller\/uiviewcontrolleranimatedtransitioning-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/fusion\/presentationcontroller\/uiviewcontrolleranimatedtransitioning-implementations"]}],"sections":[],"references":{"doc://org.cocoapods.Fusion/documentation/Fusion":{"url":"\/documentation\/fusion","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion","type":"topic","title":"Fusion","abstract":[],"role":"collection"},"doc://org.cocoapods.Fusion/documentation/Fusion/PresentationController":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController","navigatorTitle":[{"kind":"identifier","text":"PresentationController"}],"title":"PresentationController","abstract":[{"type":"text","text":"A presentation controller that has a dimming view and presents from the bottom, as a drawer behavior."}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PresentationController"}],"url":"\/documentation\/fusion\/presentationcontroller"},"doc://org.cocoapods.Fusion/documentation/Fusion/PresentationController/interruptibleAnimator(using:)":{"abstract":[],"navigatorTitle":[{"text":"interruptibleAnimatorForTransition:","kind":"identifier"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"interruptibleAnimator","kind":"identifier"},{"text":"(","kind":"text"},{"text":"using","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(pl)UIViewControllerContextTransitioning","text":"UIViewControllerContextTransitioning","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(pl)UIViewImplicitlyAnimating","text":"UIViewImplicitlyAnimating","kind":"typeIdentifier"}],"type":"topic","title":"interruptibleAnimator(using:)","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/interruptibleAnimator(using:)","url":"\/documentation\/fusion\/presentationcontroller\/interruptibleanimator(using:)","kind":"symbol"},"doc://org.cocoapods.Fusion/documentation/Fusion/PresentationController/transitionDuration(using:)":{"url":"\/documentation\/fusion\/presentationcontroller\/transitionduration(using:)","title":"transitionDuration(using:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"transitionDuration:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"transitionDuration"},{"kind":"text","text":"("},{"kind":"externalParam","text":"using"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIViewControllerContextTransitioning","text":"UIViewControllerContextTransitioning"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"}],"identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/transitionDuration(using:)","abstract":[],"role":"symbol","type":"topic"},"doc://org.cocoapods.Fusion/documentation/Fusion/PresentationController/animateTransition(using:)":{"title":"animateTransition(using:)","url":"\/documentation\/fusion\/presentationcontroller\/animatetransition(using:)","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/animateTransition(using:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"animateTransition","kind":"identifier"},{"text":"(","kind":"text"},{"text":"using","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(pl)UIViewControllerContextTransitioning","text":"UIViewControllerContextTransitioning","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"animateTransition:","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/animateTransition(using:)","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/interruptibleAnimator(using:)","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/transitionDuration(using:)"],"generated":true,"anchor":"Instance-Methods"}],"path":"\/topicSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":"PresentationController","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController\/title"},{"op":"replace","value":[{"kind":"identifier","text":"PresentationController"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"PresentationController"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController\/navigatorTitle"},{"op":"replace","value":"interruptibleAnimatorForTransition:","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController~1interruptibleAnimator(using:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"interruptibleAnimatorForTransition:"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController~1interruptibleAnimator(using:)\/fragments"},{"op":"replace","value":"transitionDuration:","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController~1transitionDuration(using:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"transitionDuration:"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController~1transitionDuration(using:)\/fragments","op":"replace"},{"value":"animateTransition:","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController~1animateTransition(using:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"animateTransition:"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController~1animateTransition(using:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}