{"identifier":{"url":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/UIHorizontalPanGestureRecognizer\/gestureRecognizerShouldBegin(_:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/fusion\/uihorizontalpangesturerecognizer\/gesturerecognizershouldbegin(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fusion\/uihorizontalpangesturerecognizer\/gesturerecognizershouldbegin(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"UIGestureRecognizerDelegate.gestureRecognizerShouldBegin(_:)","type":"codeVoice"},{"text":".","type":"text"}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"gestureRecognizerShouldBegin:"}],"title":"gestureRecognizerShouldBegin(_:)","roleHeading":"Instance Method","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"gestureRecognizerShouldBegin"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIGestureRecognizer","kind":"typeIdentifier","text":"UIGestureRecognizer"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"externalID":"c:@M@Fusion@objc(cs)UIHorizontalPanGestureRecognizer(im)gestureRecognizerShouldBegin:","modules":[{"name":"Fusion"}],"role":"symbol"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/UIHorizontalPanGestureRecognizer"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"gestureRecognizerShouldBegin"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"gestureRecognizer"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIGestureRecognizer","kind":"typeIdentifier","text":"UIGestureRecognizer"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://org.cocoapods.Fusion/documentation/Fusion/UIHorizontalPanGestureRecognizer":{"url":"\/documentation\/fusion\/uihorizontalpangesturerecognizer","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/UIHorizontalPanGestureRecognizer","navigatorTitle":[{"kind":"identifier","text":"UIHorizontalPanGestureRecognizer"}],"type":"topic","title":"UIHorizontalPanGestureRecognizer","abstract":[{"text":"Same as Pan Gesture but stricly horizontal, ideal for swipe cell\/object actions.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIHorizontalPanGestureRecognizer"}],"role":"symbol"},"doc://org.cocoapods.Fusion/documentation/Fusion":{"url":"\/documentation\/fusion","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion","type":"topic","title":"Fusion","abstract":[],"role":"collection"},"doc://org.cocoapods.Fusion/documentation/Fusion/UIHorizontalPanGestureRecognizer/gestureRecognizerShouldBegin(_:)":{"role":"symbol","url":"\/documentation\/fusion\/uihorizontalpangesturerecognizer\/gesturerecognizershouldbegin(_:)","navigatorTitle":[{"kind":"identifier","text":"gestureRecognizerShouldBegin:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"gestureRecognizerShouldBegin"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIGestureRecognizer","kind":"typeIdentifier","text":"UIGestureRecognizer"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"type":"topic","title":"gestureRecognizerShouldBegin(_:)","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/UIHorizontalPanGestureRecognizer\/gestureRecognizerShouldBegin(_:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"gestureRecognizerShouldBegin:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"gestureRecognizerShouldBegin:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"gestureRecognizerShouldBegin:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIGestureRecognizer","kind":"typeIdentifier","text":"UIGestureRecognizer"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"gestureRecognizer"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"UIHorizontalPanGestureRecognizer","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1UIHorizontalPanGestureRecognizer\/title"},{"op":"replace","value":[{"text":"UIHorizontalPanGestureRecognizer","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1UIHorizontalPanGestureRecognizer\/fragments"},{"op":"replace","value":[{"text":"UIHorizontalPanGestureRecognizer","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1UIHorizontalPanGestureRecognizer\/navigatorTitle"},{"op":"replace","value":"gestureRecognizerShouldBegin:","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1UIHorizontalPanGestureRecognizer~1gestureRecognizerShouldBegin(_:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"gestureRecognizerShouldBegin:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1UIHorizontalPanGestureRecognizer~1gestureRecognizerShouldBegin(_:)\/fragments"}]}]}