{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/UIHorizontalPanGestureRecognizer"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/fusion\/uihorizontalpangesturerecognizer\/initwithtarget:action:"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithTarget:"},{"kind":"text","text":"("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"internalParam","text":"target"},{"kind":"text","text":" "},{"kind":"identifier","text":"action:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@SEL","text":"SEL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"action"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}],"metadata":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTarget:action:"}],"symbolKind":"method","externalID":"c:@M@Fusion@objc(cs)UIHorizontalPanGestureRecognizer(im)initWithTarget:action:","title":"initWithTarget:action:","role":"symbol","modules":[{"name":"Fusion"}],"navigatorTitle":[{"kind":"identifier","text":"initWithTarget:action:"}],"roleHeading":"Instance Method"},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/UIHorizontalPanGestureRecognizer\/initWithTarget:action:"},"kind":"symbol","references":{"doc://org.cocoapods.Fusion/documentation/Fusion/UIHorizontalPanGestureRecognizer/initWithTarget:action:":{"kind":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTarget:action:"}],"title":"initWithTarget:action:","role":"symbol","abstract":[],"url":"\/documentation\/fusion\/uihorizontalpangesturerecognizer\/initwithtarget:action:","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/UIHorizontalPanGestureRecognizer\/initWithTarget:action:","navigatorTitle":[{"kind":"identifier","text":"initWithTarget:action:"}],"type":"topic"},"doc://org.cocoapods.Fusion/documentation/Fusion":{"url":"\/documentation\/fusion","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion","type":"topic","title":"Fusion","abstract":[],"role":"collection"},"doc://org.cocoapods.Fusion/documentation/Fusion/UIHorizontalPanGestureRecognizer":{"url":"\/documentation\/fusion\/uihorizontalpangesturerecognizer","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/UIHorizontalPanGestureRecognizer","navigatorTitle":[{"kind":"identifier","text":"UIHorizontalPanGestureRecognizer"}],"type":"topic","title":"UIHorizontalPanGestureRecognizer","abstract":[{"text":"Same as Pan Gesture but stricly horizontal, ideal for swipe cell\/object actions.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIHorizontalPanGestureRecognizer"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"UIHorizontalPanGestureRecognizer","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1UIHorizontalPanGestureRecognizer\/title"},{"op":"replace","value":[{"text":"UIHorizontalPanGestureRecognizer","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1UIHorizontalPanGestureRecognizer\/fragments"},{"op":"replace","value":[{"text":"UIHorizontalPanGestureRecognizer","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1UIHorizontalPanGestureRecognizer\/navigatorTitle"}]}]}