{"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion"]]},"metadata":{"symbolKind":"class","role":"symbol","externalID":"c:@M@Fusion@objc(cs)GradientView","navigatorTitle":[{"kind":"identifier","text":"GradientView"}],"modules":[{"name":"Fusion"}],"title":"GradientView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GradientView","kind":"identifier"}],"roleHeading":"Class"},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/GradientView","interfaceLanguage":"swift"},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/GradientView\/init(colors:)"],"title":"Initializers","anchor":"Initializers","generated":true},{"anchor":"Instance-Properties","generated":true,"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/GradientView\/colors","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/GradientView\/end","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/GradientView\/start","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/GradientView\/type"]},{"anchor":"Instance-Methods","generated":true,"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/GradientView\/layoutSubviews()"]}],"abstract":[{"text":"Convenience view that encpsulates the ","type":"text"},{"type":"codeVoice","code":"UIView.make(gradient:start:end:type:)"},{"type":"text","text":" and makes it automatically redrawable and adaptable."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GradientView"}],"languages":["swift"]}],"kind":"declarations"}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.Fusion\/objc(cs)UIView"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.Fusion\/objc(pl)NSCoding","doc:\/\/org.cocoapods.Fusion\/objc(pl)NSObject","doc:\/\/org.cocoapods.Fusion\/objc(pl)CALayerDelegate","doc:\/\/org.cocoapods.Fusion\/s7CVarArgP","doc:\/\/org.cocoapods.Fusion\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.Fusion\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.Fusion\/SQ","doc:\/\/org.cocoapods.Fusion\/SH","doc:\/\/org.cocoapods.Fusion\/objc(pl)UIAccessibilityIdentification","doc:\/\/org.cocoapods.Fusion\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.Fusion\/objc(pl)UIAppearance","doc:\/\/org.cocoapods.Fusion\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.Fusion\/objc(pl)UIDynamicItem","doc:\/\/org.cocoapods.Fusion\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.Fusion\/objc(pl)UIFocusItem","doc:\/\/org.cocoapods.Fusion\/objc(pl)UIFocusItemContainer","doc:\/\/org.cocoapods.Fusion\/objc(pl)UILargeContentViewerItem","doc:\/\/org.cocoapods.Fusion\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.Fusion\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/org.cocoapods.Fusion\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.Fusion\/5UIKit23UITraitChangeObservableP","doc:\/\/org.cocoapods.Fusion\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.Fusion\/objc(pl)UIUserActivityRestoring","doc:\/\/org.cocoapods.Fusion\/objc(pl)UICoordinateSpace"],"kind":"relationships"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/fusion\/gradientview"]},{"paths":["\/documentation\/fusion\/gradientview"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.Fusion/objc(cs)UIView":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Fusion\/objc(cs)UIView","title":"UIView"},"doc://org.cocoapods.Fusion/objc(pl)UIResponderStandardEditActions":{"identifier":"doc:\/\/org.cocoapods.Fusion\/objc(pl)UIResponderStandardEditActions","type":"unresolvable","title":"UIKit.UIResponderStandardEditActions"},"doc://org.cocoapods.Fusion/documentation/Fusion/GradientView/type":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/GradientView\/type","title":"type","abstract":[],"kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CAGradientLayerType","kind":"typeIdentifier","preciseIdentifier":"c:@T@CAGradientLayerType"}],"url":"\/documentation\/fusion\/gradientview\/type"},"doc://org.cocoapods.Fusion/documentation/Fusion/GradientView/colors":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"colors"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"kind":"text","text":"]"}],"title":"colors","role":"symbol","abstract":[],"url":"\/documentation\/fusion\/gradientview\/colors","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/GradientView\/colors","type":"topic"},"doc://org.cocoapods.Fusion/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/org.cocoapods.Fusion\/objc(pl)UILargeContentViewerItem"},"doc://org.cocoapods.Fusion/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIUtilities.UICoordinateSpace","identifier":"doc:\/\/org.cocoapods.Fusion\/objc(pl)UICoordinateSpace"},"doc://org.cocoapods.Fusion/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/org.cocoapods.Fusion\/objc(pl)UIFocusItem"},"doc://org.cocoapods.Fusion/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.Fusion\/s7CVarArgP"},"doc://org.cocoapods.Fusion/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.Fusion\/SH"},"doc://org.cocoapods.Fusion/documentation/Fusion/GradientView":{"title":"GradientView","url":"\/documentation\/fusion\/gradientview","abstract":[{"text":"Convenience view that encpsulates the ","type":"text"},{"code":"UIView.make(gradient:start:end:type:)","type":"codeVoice"},{"text":" and makes it automatically redrawable and adaptable.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/GradientView","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GradientView"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GradientView"}]},"doc://org.cocoapods.Fusion/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/org.cocoapods.Fusion\/objc(pl)CALayerDelegate"},"doc://org.cocoapods.Fusion/documentation/Fusion/GradientView/start":{"title":"start","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"start","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint","text":"CGPoint"}],"kind":"symbol","url":"\/documentation\/fusion\/gradientview\/start","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/GradientView\/start","abstract":[]},"doc://org.cocoapods.Fusion/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/org.cocoapods.Fusion\/objc(pl)UIPasteConfigurationSupporting"},"doc://org.cocoapods.Fusion/documentation/Fusion/GradientView/init(colors:)":{"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/GradientView\/init(colors:)","url":"\/documentation\/fusion\/gradientview\/init(colors:)","title":"init(colors:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"colors","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":"])","kind":"text"}]},"doc://org.cocoapods.Fusion/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/org.cocoapods.Fusion\/objc(pl)UIDynamicItem"},"doc://org.cocoapods.Fusion/documentation/Fusion/GradientView/initWithCoder:":{"title":"initWithCoder:","url":"\/documentation\/fusion\/gradientview\/initwithcoder:","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/GradientView\/initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}]},"doc://org.cocoapods.Fusion/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/org.cocoapods.Fusion\/objc(pl)UITraitEnvironment","type":"unresolvable","title":"UIKit.UITraitEnvironment"},"doc://org.cocoapods.Fusion/objc(pl)UIFocusItemContainer":{"identifier":"doc:\/\/org.cocoapods.Fusion\/objc(pl)UIFocusItemContainer","type":"unresolvable","title":"UIKit.UIFocusItemContainer"},"doc://org.cocoapods.Fusion/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/org.cocoapods.Fusion\/objc(pl)UIAppearanceContainer"},"doc://org.cocoapods.Fusion/documentation/Fusion":{"url":"\/documentation\/fusion","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion","type":"topic","title":"Fusion","abstract":[],"role":"collection"},"doc://org.cocoapods.Fusion/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.Fusion\/objc(pl)NSObject"},"doc://org.cocoapods.Fusion/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/org.cocoapods.Fusion\/objc(pl)UIAccessibilityIdentification"},"doc://org.cocoapods.Fusion/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/org.cocoapods.Fusion\/objc(pl)UIUserActivityRestoring"},"doc://org.cocoapods.Fusion/documentation/Fusion/GradientView/layoutSubviews()":{"url":"\/documentation\/fusion\/gradientview\/layoutsubviews()","title":"layoutSubviews()","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"layoutSubviews"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutSubviews"},{"kind":"text","text":"()"}],"identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/GradientView\/layoutSubviews()","abstract":[],"role":"symbol","type":"topic"},"doc://org.cocoapods.Fusion/documentation/Fusion/GradientView/end":{"title":"end","url":"\/documentation\/fusion\/gradientview\/end","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/GradientView\/end","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"end","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGPoint","preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier"}],"type":"topic","role":"symbol"},"doc://org.cocoapods.Fusion/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.Fusion\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.Fusion/objc(pl)UIAppearance":{"identifier":"doc:\/\/org.cocoapods.Fusion\/objc(pl)UIAppearance","type":"unresolvable","title":"UIKit.UIAppearance"},"doc://org.cocoapods.Fusion/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/org.cocoapods.Fusion\/objc(pl)NSCoding"},"doc://org.cocoapods.Fusion/objc(pl)UIFocusEnvironment":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Fusion\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment"},"doc://org.cocoapods.Fusion/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/org.cocoapods.Fusion\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://org.cocoapods.Fusion/documentation/Fusion/GradientView/initWithFrame:":{"title":"initWithFrame:","url":"\/documentation\/fusion\/gradientview\/initwithframe:","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/GradientView\/initWithFrame:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}]},"doc://org.cocoapods.Fusion/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/org.cocoapods.Fusion\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://org.cocoapods.Fusion/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.Fusion\/s23CustomStringConvertibleP"},"doc://org.cocoapods.Fusion/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.Fusion\/SQ"},"doc://org.cocoapods.Fusion/5UIKit23UITraitChangeObservableP":{"identifier":"doc:\/\/org.cocoapods.Fusion\/5UIKit23UITraitChangeObservableP","type":"unresolvable","title":"UIKit.UITraitChangeObservable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"GradientView","path":"\/metadata\/title"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"GradientView","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"GradientView","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/GradientView\/initWithCoder:","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/GradientView\/initWithFrame:","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/GradientView\/layoutSubviews()"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}],"path":"\/topicSections"},{"op":"replace","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.Fusion\/objc(cs)UIView"],"title":"Inherits From","kind":"relationships"}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"GradientView"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier","text":"UIView"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"GradientView","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1GradientView\/title"},{"op":"replace","value":[{"text":"GradientView","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1GradientView\/fragments"},{"op":"replace","value":[{"text":"GradientView","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1GradientView\/navigatorTitle"},{"op":"replace","value":"layoutSubviews","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1GradientView~1layoutSubviews()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1GradientView~1layoutSubviews()\/fragments"}]}]}