{"variants":[{"paths":["\/documentation\/fusion\/kfusioncoreversion"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fusion\/kfusioncoreversion"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"externalID":"c:FusionCore.h@kFusionCoreVersion","navigatorTitle":[{"text":"kFusionCoreVersion","kind":"identifier"}],"modules":[{"name":"Fusion"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kFusionCoreVersion","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"roleHeading":"Global Variable","symbolKind":"var","title":"kFusionCoreVersion","role":"symbol"},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kFusionCoreVersion","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion"]]},"identifier":{"url":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/kFusionCoreVersion","interfaceLanguage":"swift"},"sections":[],"references":{"doc://org.cocoapods.Fusion/documentation/Fusion/kFusionCoreVersion":{"navigatorTitle":[{"text":"kFusionCoreVersion","kind":"identifier"}],"title":"kFusionCoreVersion","type":"topic","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kFusionCoreVersion","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"kind":"symbol","url":"\/documentation\/fusion\/kfusioncoreversion","abstract":[],"identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/kFusionCoreVersion"},"doc://org.cocoapods.Fusion/documentation/Fusion":{"url":"\/documentation\/fusion","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion","type":"topic","title":"Fusion","abstract":[],"role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Global Variable","path":"\/metadata\/roleHeading","op":"replace"},{"value":"kFusionCoreVersion","path":"\/metadata\/title","op":"replace"},{"value":"var","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"kFusionCoreVersion","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"preciseIdentifier":"c:d","kind":"typeIdentifier","text":"double"},{"kind":"text","text":" "},{"kind":"identifier","text":"kFusionCoreVersion"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"kFusionCoreVersion","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1kFusionCoreVersion\/title","op":"replace"},{"value":[{"text":"kFusionCoreVersion","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1kFusionCoreVersion\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}