{"relationshipsSections":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.Fusion\/objc(cs)UIPresentationController"]},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.Fusion\/objc(pl)NSObject","doc:\/\/org.cocoapods.Fusion\/s7CVarArgP","doc:\/\/org.cocoapods.Fusion\/s8CopyableP","doc:\/\/org.cocoapods.Fusion\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.Fusion\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.Fusion\/SQ","doc:\/\/org.cocoapods.Fusion\/SH","doc:\/\/org.cocoapods.Fusion\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.Fusion\/objc(pl)UIContentContainer","doc:\/\/org.cocoapods.Fusion\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.Fusion\/5UIKit23UITraitChangeObservableP","doc:\/\/org.cocoapods.Fusion\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.Fusion\/objc(pl)UIViewControllerAnimatedTransitioning","doc:\/\/org.cocoapods.Fusion\/objc(pl)UIViewControllerTransitioningDelegate"]}],"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/Config"],"title":"Structures","generated":true,"anchor":"Structures"},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/allowsDismiss","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/allowsInteractiveTransition","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/cornerRadius","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/dimmingView","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/extraSafeArea","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/frameOfPresentedViewInContainerView","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/isGrabberVisible","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/onDismissal","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/picInPic","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/presentingSide"],"generated":true,"anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/dismissalTransitionDidEnd(_:)","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/dismissalTransitionWillBegin()","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/preferredContentSizeDidChange(forChildContentContainer:)","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/prepareFinalLayout(source:)","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/prepareInitialLayout(closing:)","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/presentationTransitionWillBegin()"],"generated":true,"anchor":"Instance-Methods"},{"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/UIViewControllerAnimatedTransitioning-Implementations","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/UIViewControllerTransitioningDelegate-Implementations"],"generated":true,"anchor":"Default-Implementations"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PresentationController","kind":"identifier"}],"platforms":["iOS"]}]}],"abstract":[{"type":"text","text":"A presentation controller that has a dimming view and presents from the bottom, as a drawer behavior."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/fusion\/presentationcontroller"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/fusion\/presentationcontroller"]}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController"},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"title":"PresentationController","roleHeading":"Class","modules":[{"name":"Fusion"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PresentationController","kind":"identifier"}],"externalID":"c:@M@Fusion@objc(cs)PresentationController","role":"symbol","symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"PresentationController"}]},"references":{"doc://org.cocoapods.Fusion/documentation/Fusion/PresentationController/frameOfPresentedViewInContainerView":{"url":"\/documentation\/fusion\/presentationcontroller\/frameofpresentedviewincontainerview","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"frameOfPresentedViewInContainerView"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"frameOfPresentedViewInContainerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"}],"identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/frameOfPresentedViewInContainerView","type":"topic","title":"frameOfPresentedViewInContainerView","abstract":[]},"doc://org.cocoapods.Fusion/documentation/Fusion/PresentationController/presentationTransitionWillBegin()":{"url":"\/documentation\/fusion\/presentationcontroller\/presentationtransitionwillbegin()","title":"presentationTransitionWillBegin()","kind":"symbol","navigatorTitle":[{"text":"presentationTransitionWillBegin","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"presentationTransitionWillBegin","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/presentationTransitionWillBegin()","abstract":[],"role":"symbol","type":"topic"},"doc://org.cocoapods.Fusion/documentation/Fusion/PresentationController/onDismissal":{"title":"onDismissal","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onDismissal","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Callback","preciseIdentifier":"s:6Fusion8Callbacka","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","url":"\/documentation\/fusion\/presentationcontroller\/ondismissal","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/onDismissal","abstract":[{"text":"A closure to be executed after the presentation is dismissed in the future.","type":"text"}]},"doc://org.cocoapods.Fusion/objc(cs)UIPresentationController":{"identifier":"doc:\/\/org.cocoapods.Fusion\/objc(cs)UIPresentationController","title":"UIPresentationController","type":"unresolvable"},"doc://org.cocoapods.Fusion/documentation/Fusion/PresentationController/preferredContentSizeDidChange(forChildContentContainer:)":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"preferredContentSizeDidChangeForChildContentContainer:"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferredContentSizeDidChange"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forChildContentContainer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIContentContainer","text":"UIContentContainer"},{"kind":"text","text":")"}],"type":"topic","title":"preferredContentSizeDidChange(forChildContentContainer:)","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/preferredContentSizeDidChange(forChildContentContainer:)","url":"\/documentation\/fusion\/presentationcontroller\/preferredcontentsizedidchange(forchildcontentcontainer:)","kind":"symbol"},"doc://org.cocoapods.Fusion/documentation/Fusion/PresentationController/picInPic":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"picInPic"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic","title":"picInPic","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/picInPic","url":"\/documentation\/fusion\/presentationcontroller\/picinpic","abstract":[{"type":"text","text":"Keeps the previous View Controller visible on top, the return navigation is done by tapping on it."}]},"doc://org.cocoapods.Fusion/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.Fusion\/SH","type":"unresolvable"},"doc://org.cocoapods.Fusion/objc(pl)UIViewControllerTransitioningDelegate":{"title":"UIViewControllerTransitioningDelegate","identifier":"doc:\/\/org.cocoapods.Fusion\/objc(pl)UIViewControllerTransitioningDelegate","type":"unresolvable"},"doc://org.cocoapods.Fusion/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.Fusion\/s7CVarArgP","type":"unresolvable"},"doc://org.cocoapods.Fusion/documentation/Fusion/PresentationController/allowsInteractiveTransition":{"title":"allowsInteractiveTransition","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowsInteractiveTransition"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"kind":"symbol","url":"\/documentation\/fusion\/presentationcontroller\/allowsinteractivetransition","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/allowsInteractiveTransition","abstract":[{"type":"text","text":"Indicates if the user is allowed to interactively move the transition. The default value is "},{"code":"true","type":"codeVoice"},{"type":"text","text":"."}]},"doc://org.cocoapods.Fusion/s8CopyableP":{"title":"Swift.Copyable","identifier":"doc:\/\/org.cocoapods.Fusion\/s8CopyableP","type":"unresolvable"},"doc://org.cocoapods.Fusion/documentation/Fusion/PresentationController/presentingSide":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/presentingSide","title":"presentingSide","abstract":[{"type":"text","text":"Defines the presenting side of the new controller."}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentingSide"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@UIRectEdge","kind":"typeIdentifier","text":"UIRectEdge"}],"url":"\/documentation\/fusion\/presentationcontroller\/presentingside"},"doc://org.cocoapods.Fusion/documentation/Fusion/PresentationController/Config":{"navigatorTitle":[{"kind":"identifier","text":"Config"}],"title":"PresentationController.Config","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Config"}],"kind":"symbol","url":"\/documentation\/fusion\/presentationcontroller\/config","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/Config","abstract":[]},"doc://org.cocoapods.Fusion/documentation/Fusion/PresentationController/prepareFinalLayout(source:)":{"abstract":[],"kind":"symbol","role":"symbol","type":"topic","title":"prepareFinalLayout(source:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"prepareFinalLayout","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"source"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"kind":"text","text":"?)"}],"url":"\/documentation\/fusion\/presentationcontroller\/preparefinallayout(source:)","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/prepareFinalLayout(source:)"},"doc://org.cocoapods.Fusion/documentation/Fusion/PresentationController/prepareInitialLayout(closing:)":{"title":"prepareInitialLayout(closing:)","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"prepareInitialLayout"},{"kind":"text","text":"("},{"kind":"externalParam","text":"closing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"kind":"symbol","url":"\/documentation\/fusion\/presentationcontroller\/prepareinitiallayout(closing:)","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/prepareInitialLayout(closing:)","abstract":[]},"doc://org.cocoapods.Fusion/objc(pl)UITraitEnvironment":{"title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/org.cocoapods.Fusion\/objc(pl)UITraitEnvironment","type":"unresolvable"},"doc://org.cocoapods.Fusion/documentation/Fusion/PresentationController/dismissalTransitionWillBegin()":{"abstract":[],"kind":"symbol","role":"symbol","type":"topic","title":"dismissalTransitionWillBegin()","navigatorTitle":[{"kind":"identifier","text":"dismissalTransitionWillBegin"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dismissalTransitionWillBegin","kind":"identifier"},{"text":"()","kind":"text"}],"url":"\/documentation\/fusion\/presentationcontroller\/dismissaltransitionwillbegin()","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/dismissalTransitionWillBegin()"},"doc://org.cocoapods.Fusion/documentation/Fusion/PresentationController/UIViewControllerAnimatedTransitioning-Implementations":{"kind":"article","role":"collectionGroup","type":"topic","title":"UIViewControllerAnimatedTransitioning Implementations","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/UIViewControllerAnimatedTransitioning-Implementations","url":"\/documentation\/fusion\/presentationcontroller\/uiviewcontrolleranimatedtransitioning-implementations","abstract":[]},"doc://org.cocoapods.Fusion/objc(pl)UIViewControllerAnimatedTransitioning":{"title":"UIViewControllerAnimatedTransitioning","identifier":"doc:\/\/org.cocoapods.Fusion\/objc(pl)UIViewControllerAnimatedTransitioning","type":"unresolvable"},"doc://org.cocoapods.Fusion/documentation/Fusion":{"url":"\/documentation\/fusion","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion","type":"topic","title":"Fusion","abstract":[],"role":"collection"},"doc://org.cocoapods.Fusion/documentation/Fusion/PresentationController/dimmingView":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dimmingView"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier","text":"UIView"}],"title":"dimmingView","role":"symbol","abstract":[{"type":"text","text":"The dimming view. This property can be used to customize the dimming view."}],"url":"\/documentation\/fusion\/presentationcontroller\/dimmingview","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/dimmingView","type":"topic"},"doc://org.cocoapods.Fusion/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.Fusion\/objc(pl)NSObject","type":"unresolvable"},"doc://org.cocoapods.Fusion/objc(pl)UIAppearanceContainer":{"title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/org.cocoapods.Fusion\/objc(pl)UIAppearanceContainer","type":"unresolvable"},"doc://org.cocoapods.Fusion/documentation/Fusion/PresentationController/isGrabberVisible":{"kind":"symbol","title":"isGrabberVisible","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/isGrabberVisible","abstract":[{"type":"text","text":"Indicates if a grabber will be visible for interaction. The default value is "},{"code":"false","type":"codeVoice"},{"type":"text","text":"."}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isGrabberVisible"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/fusion\/presentationcontroller\/isgrabbervisible","type":"topic"},"doc://org.cocoapods.Fusion/objc(pl)UIContentContainer":{"title":"UIKit.UIContentContainer","identifier":"doc:\/\/org.cocoapods.Fusion\/objc(pl)UIContentContainer","type":"unresolvable"},"doc://org.cocoapods.Fusion/documentation/Fusion/PresentationController/extraSafeArea":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"extraSafeArea"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"}],"type":"topic","title":"extraSafeArea","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/extraSafeArea","url":"\/documentation\/fusion\/presentationcontroller\/extrasafearea","abstract":[{"type":"text","text":"Defines a safe space at the top that will never be exceeded, this is in addition to any top existing window safe."}]},"doc://org.cocoapods.Fusion/documentation/Fusion/PresentationController/UIViewControllerTransitioningDelegate-Implementations":{"kind":"article","role":"collectionGroup","type":"topic","title":"UIViewControllerTransitioningDelegate Implementations","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/UIViewControllerTransitioningDelegate-Implementations","url":"\/documentation\/fusion\/presentationcontroller\/uiviewcontrollertransitioningdelegate-implementations","abstract":[]},"doc://org.cocoapods.Fusion/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.Fusion\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://org.cocoapods.Fusion/documentation/Fusion/PresentationController":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController","navigatorTitle":[{"kind":"identifier","text":"PresentationController"}],"title":"PresentationController","abstract":[{"type":"text","text":"A presentation controller that has a dimming view and presents from the bottom, as a drawer behavior."}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PresentationController"}],"url":"\/documentation\/fusion\/presentationcontroller"},"doc://org.cocoapods.Fusion/objc(pl)UIFocusEnvironment":{"title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/org.cocoapods.Fusion\/objc(pl)UIFocusEnvironment","type":"unresolvable"},"doc://org.cocoapods.Fusion/documentation/Fusion/PresentationController/cornerRadius":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cornerRadius","kind":"identifier"},{"text":": ","kind":"text"},{"text":"RectCorners","preciseIdentifier":"s:6Fusion11RectCornersV","kind":"typeIdentifier"}],"title":"cornerRadius","role":"symbol","abstract":[{"text":"The corner radius of the drawer frame.","type":"text"}],"url":"\/documentation\/fusion\/presentationcontroller\/cornerradius","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/cornerRadius","kind":"symbol"},"doc://org.cocoapods.Fusion/documentation/Fusion/PresentationController/allowsDismiss":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowsDismiss"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic","title":"allowsDismiss","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/allowsDismiss","url":"\/documentation\/fusion\/presentationcontroller\/allowsdismiss","abstract":[{"type":"text","text":"Indicates if the user is allowed to dismiss it manually. When set to "},{"code":"false","type":"codeVoice"},{"type":"text","text":" user won’t be albe to tap to dismiss, however it still"},{"type":"text","text":" "},{"type":"text","text":"dismissable programatically. The default value is "},{"code":"true","type":"codeVoice"},{"type":"text","text":"."}]},"doc://org.cocoapods.Fusion/documentation/Fusion/PresentationController/dismissalTransitionDidEnd(_:)":{"url":"\/documentation\/fusion\/presentationcontroller\/dismissaltransitiondidend(_:)","role":"symbol","navigatorTitle":[{"text":"dismissalTransitionDidEnd:","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dismissalTransitionDidEnd","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/dismissalTransitionDidEnd(_:)","type":"topic","abstract":[],"title":"dismissalTransitionDidEnd(_:)"},"doc://org.cocoapods.Fusion/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.Fusion\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://org.cocoapods.Fusion/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.Fusion\/SQ","type":"unresolvable"},"doc://org.cocoapods.Fusion/5UIKit23UITraitChangeObservableP":{"title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/org.cocoapods.Fusion\/5UIKit23UITraitChangeObservableP","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"PresentationController","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"PresentationController","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"PresentationController","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/frameOfPresentedViewInContainerView"],"anchor":"Instance-Properties"},{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/dismissalTransitionDidEnd(_:)","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/dismissalTransitionWillBegin()","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/preferredContentSizeDidChange(forChildContentContainer:)","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/presentationTransitionWillBegin()"],"anchor":"Instance-Methods"},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/UIViewControllerAnimatedTransitioning-Implementations","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/PresentationController\/UIViewControllerTransitioningDelegate-Implementations"],"anchor":"Default-Implementations"}],"path":"\/topicSections"},{"op":"replace","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.Fusion\/objc(cs)UIPresentationController"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.Fusion\/objc(pl)UIViewControllerAnimatedTransitioning","doc:\/\/org.cocoapods.Fusion\/objc(pl)UIViewControllerTransitioningDelegate"],"type":"conformsTo"}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PresentationController","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"UIPresentationController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIPresentationController"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"frameOfPresentedViewInContainerView","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController~1frameOfPresentedViewInContainerView\/title"},{"op":"replace","value":[{"text":"frameOfPresentedViewInContainerView","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController~1frameOfPresentedViewInContainerView\/fragments"},{"op":"replace","value":"presentationTransitionWillBegin","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController~1presentationTransitionWillBegin()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"presentationTransitionWillBegin","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController~1presentationTransitionWillBegin()\/fragments"},{"op":"replace","value":"preferredContentSizeDidChangeForChildContentContainer:","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController~1preferredContentSizeDidChange(forChildContentContainer:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"preferredContentSizeDidChangeForChildContentContainer:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController~1preferredContentSizeDidChange(forChildContentContainer:)\/fragments"},{"op":"replace","value":"dismissalTransitionWillBegin","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController~1dismissalTransitionWillBegin()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"dismissalTransitionWillBegin","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController~1dismissalTransitionWillBegin()\/fragments"},{"op":"replace","value":"PresentationController","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController\/title"},{"op":"replace","value":[{"text":"PresentationController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController\/fragments"},{"op":"replace","value":[{"text":"PresentationController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController\/navigatorTitle"},{"op":"replace","value":"dismissalTransitionDidEnd:","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController~1dismissalTransitionDidEnd(_:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"dismissalTransitionDidEnd:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1PresentationController~1dismissalTransitionDidEnd(_:)\/fragments"}]}]}