{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion"]]},"metadata":{"externalID":"c:@M@Fusion@objc(cs)RESTAuthenticator","navigatorTitle":[{"kind":"identifier","text":"RESTAuthenticator"}],"modules":[{"name":"Fusion"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RESTAuthenticator","kind":"identifier"}],"roleHeading":"Class","symbolKind":"class","role":"symbol","title":"RESTAuthenticator"},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/RESTAuthenticator\/hashKeys"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/RESTAuthenticator\/urlSession(_:didReceive:completionHandler:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"},{"identifiers":["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/RESTAuthenticator\/session","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/RESTAuthenticator\/shared"],"title":"Type Properties","generated":true,"anchor":"Type-Properties"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/fusion\/restauthenticator"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/fusion\/restauthenticator"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/RESTAuthenticator"},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.Fusion\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.Fusion\/objc(pl)NSURLSessionDelegate","doc:\/\/org.cocoapods.Fusion\/objc(pl)NSObject","doc:\/\/org.cocoapods.Fusion\/s7CVarArgP","doc:\/\/org.cocoapods.Fusion\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.Fusion\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.Fusion\/SQ","doc:\/\/org.cocoapods.Fusion\/SH","doc:\/\/org.cocoapods.Fusion\/s8SendableP","doc:\/\/org.cocoapods.Fusion\/s16SendableMetatypeP"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RESTAuthenticator","kind":"identifier"}],"platforms":["iOS"]}]}],"sections":[],"references":{"doc://org.cocoapods.Fusion/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.Fusion\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://org.cocoapods.Fusion/documentation/Fusion/RESTAuthenticator/session":{"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/RESTAuthenticator\/session","url":"\/documentation\/fusion\/restauthenticator\/session","title":"session","abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"session","kind":"identifier"},{"text":": ","kind":"text"},{"text":"URLSession","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLSession"}]},"doc://org.cocoapods.Fusion/documentation/Fusion/RESTAuthenticator/shared":{"type":"topic","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/RESTAuthenticator\/shared","kind":"symbol","abstract":[],"url":"\/documentation\/fusion\/restauthenticator\/shared","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RESTAuthenticator","preciseIdentifier":"c:@M@Fusion@objc(cs)RESTAuthenticator"}],"title":"shared"},"doc://org.cocoapods.Fusion/documentation/Fusion/RESTAuthenticator/urlSession(_:didReceive:completionHandler:)":{"url":"\/documentation\/fusion\/restauthenticator\/urlsession(_:didreceive:completionhandler:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"URLSession:didReceiveChallenge:completionHandler:"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"urlSession"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLSession","text":"URLSession"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLAuthenticationChallenge","text":"URLAuthenticationChallenge"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLSession","text":"URLSession"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@NSURLSessionAuthChallengeDisposition","text":"AuthChallengeDisposition"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLCredential","text":"URLCredential"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/RESTAuthenticator\/urlSession(_:didReceive:completionHandler:)","type":"topic","title":"urlSession(_:didReceive:completionHandler:)","abstract":[]},"doc://org.cocoapods.Fusion/documentation/Fusion":{"url":"\/documentation\/fusion","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion","type":"topic","title":"Fusion","abstract":[],"role":"collection"},"doc://org.cocoapods.Fusion/documentation/Fusion/RESTAuthenticator/hashKeys":{"url":"\/documentation\/fusion\/restauthenticator\/hashkeys","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hashKeys"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"]"}],"identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/RESTAuthenticator\/hashKeys","type":"topic","title":"hashKeys","abstract":[]},"doc://org.cocoapods.Fusion/s8SendableP":{"title":"Swift.Sendable","identifier":"doc:\/\/org.cocoapods.Fusion\/s8SendableP","type":"unresolvable"},"doc://org.cocoapods.Fusion/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.Fusion\/SQ","type":"unresolvable"},"doc://org.cocoapods.Fusion/objc(pl)NSURLSessionDelegate":{"title":"NSURLSessionDelegate","identifier":"doc:\/\/org.cocoapods.Fusion\/objc(pl)NSURLSessionDelegate","type":"unresolvable"},"doc://org.cocoapods.Fusion/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.Fusion\/SH","type":"unresolvable"},"doc://org.cocoapods.Fusion/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.Fusion\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://org.cocoapods.Fusion/s16SendableMetatypeP":{"title":"Swift.SendableMetatype","identifier":"doc:\/\/org.cocoapods.Fusion\/s16SendableMetatypeP","type":"unresolvable"},"doc://org.cocoapods.Fusion/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/org.cocoapods.Fusion\/objc(cs)NSObject","type":"unresolvable"},"doc://org.cocoapods.Fusion/documentation/Fusion/RESTAuthenticator/init":{"url":"\/documentation\/fusion\/restauthenticator\/init","title":"init","kind":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/RESTAuthenticator\/init","abstract":[],"role":"symbol","type":"topic"},"doc://org.cocoapods.Fusion/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.Fusion\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://org.cocoapods.Fusion/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.Fusion\/objc(pl)NSObject","type":"unresolvable"},"doc://org.cocoapods.Fusion/documentation/Fusion/RESTAuthenticator":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"RESTAuthenticator","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/RESTAuthenticator","url":"\/documentation\/fusion\/restauthenticator","title":"RESTAuthenticator","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RESTAuthenticator","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"RESTAuthenticator","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"RESTAuthenticator","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"RESTAuthenticator","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/RESTAuthenticator\/init","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/RESTAuthenticator\/urlSession(_:didReceive:completionHandler:)"],"anchor":"Instance-Methods"}],"path":"\/topicSections"},{"op":"replace","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.Fusion\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.Fusion\/objc(pl)NSURLSessionDelegate"],"type":"conformsTo"}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RESTAuthenticator","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"URLSession:didReceiveChallenge:completionHandler:","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1RESTAuthenticator~1urlSession(_:didReceive:completionHandler:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"URLSession:didReceiveChallenge:completionHandler:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1RESTAuthenticator~1urlSession(_:didReceive:completionHandler:)\/fragments"},{"op":"replace","value":"RESTAuthenticator","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1RESTAuthenticator\/title"},{"op":"replace","value":[{"text":"RESTAuthenticator","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1RESTAuthenticator\/fragments"},{"op":"replace","value":[{"text":"RESTAuthenticator","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1RESTAuthenticator\/navigatorTitle"}]}]}