{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIHorizontalPanGestureRecognizer"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"symbolKind":"class","navigatorTitle":[{"text":"UIHorizontalPanGestureRecognizer","kind":"identifier"}],"externalID":"c:@M@Fusion@objc(cs)UIHorizontalPanGestureRecognizer","roleHeading":"Class","title":"UIHorizontalPanGestureRecognizer","role":"symbol","modules":[{"name":"Fusion"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIHorizontalPanGestureRecognizer"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion"]]},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/UIHorizontalPanGestureRecognizer\/gestureRecognizerShouldBegin(_:)"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true}],"identifier":{"url":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/UIHorizontalPanGestureRecognizer","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.Fusion\/objc(cs)UIPanGestureRecognizer"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"identifiers":["doc:\/\/org.cocoapods.Fusion\/objc(pl)NSObject","doc:\/\/org.cocoapods.Fusion\/s7CVarArgP","doc:\/\/org.cocoapods.Fusion\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.Fusion\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.Fusion\/SQ","doc:\/\/org.cocoapods.Fusion\/SH","doc:\/\/org.cocoapods.Fusion\/objc(pl)UIGestureRecognizerDelegate"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"abstract":[{"text":"Same as Pan Gesture but stricly horizontal, ideal for swipe cell\/object actions.","type":"text"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/fusion\/uihorizontalpangesturerecognizer"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/fusion\/uihorizontalpangesturerecognizer"]}],"references":{"doc://org.cocoapods.Fusion/documentation/Fusion/UIHorizontalPanGestureRecognizer":{"url":"\/documentation\/fusion\/uihorizontalpangesturerecognizer","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/UIHorizontalPanGestureRecognizer","navigatorTitle":[{"kind":"identifier","text":"UIHorizontalPanGestureRecognizer"}],"type":"topic","title":"UIHorizontalPanGestureRecognizer","abstract":[{"text":"Same as Pan Gesture but stricly horizontal, ideal for swipe cell\/object actions.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIHorizontalPanGestureRecognizer"}],"role":"symbol"},"doc://org.cocoapods.Fusion/documentation/Fusion":{"url":"\/documentation\/fusion","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion","type":"topic","title":"Fusion","abstract":[],"role":"collection"},"doc://org.cocoapods.Fusion/objc(cs)UIPanGestureRecognizer":{"type":"unresolvable","title":"UIPanGestureRecognizer","identifier":"doc:\/\/org.cocoapods.Fusion\/objc(cs)UIPanGestureRecognizer"},"doc://org.cocoapods.Fusion/documentation/Fusion/UIHorizontalPanGestureRecognizer/initWithTarget:action:":{"kind":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTarget:action:"}],"title":"initWithTarget:action:","role":"symbol","abstract":[],"url":"\/documentation\/fusion\/uihorizontalpangesturerecognizer\/initwithtarget:action:","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/UIHorizontalPanGestureRecognizer\/initWithTarget:action:","navigatorTitle":[{"kind":"identifier","text":"initWithTarget:action:"}],"type":"topic"},"doc://org.cocoapods.Fusion/SQ":{"identifier":"doc:\/\/org.cocoapods.Fusion\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://org.cocoapods.Fusion/SH":{"identifier":"doc:\/\/org.cocoapods.Fusion\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://org.cocoapods.Fusion/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.Fusion\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.Fusion/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.Fusion\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.Fusion/documentation/Fusion/UIHorizontalPanGestureRecognizer/gestureRecognizerShouldBegin(_:)":{"role":"symbol","url":"\/documentation\/fusion\/uihorizontalpangesturerecognizer\/gesturerecognizershouldbegin(_:)","navigatorTitle":[{"kind":"identifier","text":"gestureRecognizerShouldBegin:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"gestureRecognizerShouldBegin"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIGestureRecognizer","kind":"typeIdentifier","text":"UIGestureRecognizer"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"type":"topic","title":"gestureRecognizerShouldBegin(_:)","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/UIHorizontalPanGestureRecognizer\/gestureRecognizerShouldBegin(_:)"},"doc://org.cocoapods.Fusion/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.Fusion\/s7CVarArgP"},"doc://org.cocoapods.Fusion/objc(pl)UIGestureRecognizerDelegate":{"type":"unresolvable","title":"UIGestureRecognizerDelegate","identifier":"doc:\/\/org.cocoapods.Fusion\/objc(pl)UIGestureRecognizerDelegate"},"doc://org.cocoapods.Fusion/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.Fusion\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"UIHorizontalPanGestureRecognizer"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"UIHorizontalPanGestureRecognizer"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UIHorizontalPanGestureRecognizer"}]},{"op":"replace","value":[{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/UIHorizontalPanGestureRecognizer\/gestureRecognizerShouldBegin(_:)","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/UIHorizontalPanGestureRecognizer\/initWithTarget:action:"],"generated":true}],"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.Fusion\/objc(cs)UIPanGestureRecognizer"],"title":"Inherits From","kind":"relationships"},{"type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.Fusion\/objc(pl)UIGestureRecognizerDelegate"],"title":"Conforms To","kind":"relationships"}]},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIHorizontalPanGestureRecognizer"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)UIPanGestureRecognizer","kind":"typeIdentifier","text":"UIPanGestureRecognizer"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1UIHorizontalPanGestureRecognizer\/title","op":"replace","value":"UIHorizontalPanGestureRecognizer"},{"value":[{"kind":"identifier","text":"UIHorizontalPanGestureRecognizer"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1UIHorizontalPanGestureRecognizer\/fragments","op":"replace"},{"value":[{"text":"UIHorizontalPanGestureRecognizer","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1UIHorizontalPanGestureRecognizer\/navigatorTitle","op":"replace"},{"op":"replace","value":"gestureRecognizerShouldBegin:","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1UIHorizontalPanGestureRecognizer~1gestureRecognizerShouldBegin(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"gestureRecognizerShouldBegin:"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1UIHorizontalPanGestureRecognizer~1gestureRecognizerShouldBegin(_:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}