{"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/RESTAuthenticator"]]},"metadata":{"symbolKind":"property","role":"symbol","externalID":"s:6Fusion17RESTAuthenticatorC7sessionSo12NSURLSessionCvpZ","modules":[{"name":"Fusion"}],"title":"session","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"session","kind":"identifier"},{"text":": ","kind":"text"},{"text":"URLSession","preciseIdentifier":"c:objc(cs)NSURLSession","kind":"typeIdentifier"}],"roleHeading":"Type Property"},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/RESTAuthenticator\/session"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"session"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLSession","preciseIdentifier":"c:objc(cs)NSURLSession"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/fusion\/restauthenticator\/session"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://org.cocoapods.Fusion/documentation/Fusion":{"url":"\/documentation\/fusion","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion","type":"topic","title":"Fusion","abstract":[],"role":"collection"},"doc://org.cocoapods.Fusion/documentation/Fusion/RESTAuthenticator/session":{"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/RESTAuthenticator\/session","url":"\/documentation\/fusion\/restauthenticator\/session","title":"session","abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"session","kind":"identifier"},{"text":": ","kind":"text"},{"text":"URLSession","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLSession"}]},"doc://org.cocoapods.Fusion/documentation/Fusion/RESTAuthenticator":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"RESTAuthenticator","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/RESTAuthenticator","url":"\/documentation\/fusion\/restauthenticator","title":"RESTAuthenticator","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RESTAuthenticator","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"RESTAuthenticator","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1RESTAuthenticator\/title"},{"op":"replace","value":[{"text":"RESTAuthenticator","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1RESTAuthenticator\/fragments"},{"op":"replace","value":[{"text":"RESTAuthenticator","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1RESTAuthenticator\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}