{"identifier":{"url":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/RESTAuthenticator\/urlSession(_:didReceive:completionHandler:)","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"URLSessionDelegate.urlSession(_:didReceive:completionHandler:)"},{"text":".","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/fusion\/restauthenticator\/urlsession(_:didreceive:completionhandler:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/fusion\/restauthenticator\/urlsession(_:didreceive:completionhandler:)"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"urlSession","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"session","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"URLSession","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLSession"},{"text":", ","kind":"text"},{"text":"didReceive","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"challenge","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"URLAuthenticationChallenge","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLAuthenticationChallenge"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"text":"URLSession","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLSession"},{"text":".","kind":"text"},{"text":"AuthChallengeDisposition","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSURLSessionAuthChallengeDisposition"},{"text":", ","kind":"text"},{"text":"URLCredential","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLCredential"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"roleHeading":"Instance Method","modules":[{"name":"Fusion"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"urlSession","kind":"identifier"},{"text":"(","kind":"text"},{"text":"URLSession","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLSession"},{"text":", ","kind":"text"},{"text":"didReceive","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URLAuthenticationChallenge","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLAuthenticationChallenge"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"URLSession","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLSession"},{"text":".","kind":"text"},{"text":"AuthChallengeDisposition","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSURLSessionAuthChallengeDisposition"},{"text":", ","kind":"text"},{"text":"URLCredential","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLCredential"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"externalID":"c:@M@Fusion@objc(cs)RESTAuthenticator(im)URLSession:didReceiveChallenge:completionHandler:","role":"symbol","navigatorTitle":[{"text":"URLSession:didReceiveChallenge:completionHandler:","kind":"identifier"}],"symbolKind":"method","title":"urlSession(_:didReceive:completionHandler:)"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion","doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/RESTAuthenticator"]]},"sections":[],"references":{"doc://org.cocoapods.Fusion/documentation/Fusion":{"url":"\/documentation\/fusion","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion","type":"topic","title":"Fusion","abstract":[],"role":"collection"},"doc://org.cocoapods.Fusion/documentation/Fusion/RESTAuthenticator":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"RESTAuthenticator","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/RESTAuthenticator","url":"\/documentation\/fusion\/restauthenticator","title":"RESTAuthenticator","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RESTAuthenticator","kind":"identifier"}]},"doc://org.cocoapods.Fusion/documentation/Fusion/RESTAuthenticator/urlSession(_:didReceive:completionHandler:)":{"url":"\/documentation\/fusion\/restauthenticator\/urlsession(_:didreceive:completionhandler:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"URLSession:didReceiveChallenge:completionHandler:"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"urlSession"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLSession","text":"URLSession"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLAuthenticationChallenge","text":"URLAuthenticationChallenge"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLSession","text":"URLSession"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@NSURLSessionAuthChallengeDisposition","text":"AuthChallengeDisposition"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLCredential","text":"URLCredential"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.Fusion\/documentation\/Fusion\/RESTAuthenticator\/urlSession(_:didReceive:completionHandler:)","type":"topic","title":"urlSession(_:didReceive:completionHandler:)","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"URLSession:didReceiveChallenge:completionHandler:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"URLSession:didReceiveChallenge:completionHandler:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"URLSession:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSURLSession","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLSession"},{"text":" *) ","kind":"text"},{"text":"session","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didReceiveChallenge:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSURLAuthenticationChallenge","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLAuthenticationChallenge"},{"text":" *) ","kind":"text"},{"text":"challenge","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completionHandler:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":" (^)(","kind":"text"},{"text":"NSURLSessionAuthChallengeDisposition","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSURLSessionAuthChallengeDisposition"},{"text":" ","kind":"text"},{"text":"","kind":"internalParam"},{"text":", ","kind":"text"},{"text":"NSURLCredential","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLCredential"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completionHandler","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","value":"RESTAuthenticator","path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1RESTAuthenticator\/title"},{"op":"replace","value":[{"text":"RESTAuthenticator","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1RESTAuthenticator\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1RESTAuthenticator\/navigatorTitle","value":[{"text":"RESTAuthenticator","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1RESTAuthenticator~1urlSession(_:didReceive:completionHandler:)\/title","value":"URLSession:didReceiveChallenge:completionHandler:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Fusion~1documentation~1Fusion~1RESTAuthenticator~1urlSession(_:didReceive:completionHandler:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"URLSession:didReceiveChallenge:completionHandler:","kind":"identifier"}],"op":"replace"}]}]}